# Generated by Django 5.0.2 on 2026-02-05 19:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrole',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rol de Usuario', 'verbose_name_plural': 'Roles de Usuarios'},
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='assigned_at',
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrole',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='role',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación'),
        ),
    ]
