# Generated by Django 5.0.2 on 2026-02-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Cuándo se eliminó (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('rif', models.CharField(blank=True, max_length=30, verbose_name='RIF')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('contacto_nombre', models.CharField(blank=True, max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'inventario_supplier',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['activo'], name='inventario__activo_644455_idx')],
            },
        ),
    ]
