# Generated by Django 6.0.1 on 2026-01-08 16:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acueducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Acueducto',
                'verbose_name_plural': 'Acueductos',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='OrganizacionCentral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('rif', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name': 'Organización Central',
                'verbose_name_plural': 'Organizaciones Centrales',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True)),
                ('marca', models.CharField(blank=True, max_length=150)),
                ('modelo', models.CharField(blank=True, max_length=150)),
                ('potencia_hp', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('numero_serie', models.CharField(max_length=150, unique=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='inventario.categoria')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='AlertaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umbral_minimo', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('acueducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='inventario.acueducto')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.equipo')),
            ],
            options={
                'verbose_name': 'Alerta de Stock',
                'verbose_name_plural': 'Alertas de Stock',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('TRANSFERENCIA', 'Transferencia'), ('AJUSTE', 'Ajuste')], max_length=20)),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('razon', models.TextField(blank=True)),
                ('acueducto_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_entrada', to='inventario.acueducto')),
                ('acueducto_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_salida', to='inventario.acueducto')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.equipo')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
            },
        ),
        migrations.CreateModel(
            name='InventoryAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo_tipo', models.CharField(blank=True, choices=[('TUBERIA', 'Tubería'), ('EQUIPO', 'Equipo')], max_length=20)),
                ('articulo_nombre', models.CharField(blank=True, max_length=250)),
                ('tipo_movimiento', models.CharField(blank=True, max_length=20)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SUCCESS', 'Exitoso'), ('FAILED', 'Fallido')], default='PENDING', max_length=20)),
                ('mensaje', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('acueducto_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventario.acueducto')),
                ('acueducto_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventario.acueducto')),
                ('movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='inventario.movimientoinventario')),
            ],
            options={
                'verbose_name': 'Auditoría de Inventario',
                'verbose_name_plural': 'Auditorías de Inventario',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('enviada', models.BooleanField(default=False)),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('alerta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='inventario.alertastock')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('organizacion_central', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sucursales', to='inventario.organizacioncentral')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
            },
        ),
        migrations.AddField(
            model_name='acueducto',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acueductos', to='inventario.sucursal'),
        ),
        migrations.CreateModel(
            name='Tuberia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True)),
                ('material', models.CharField(choices=[('PVC', 'PVC'), ('HIERRO', 'Hierro Dúctil'), ('CEMENTO', 'Cemento'), ('OTRO', 'Otro')], max_length=20)),
                ('tipo_uso', models.CharField(choices=[('POTABLE', 'Aguas Potables'), ('SERVIDAS', 'Aguas Servidas'), ('RIEGO', 'Riego')], max_length=20)),
                ('diametro_nominal_mm', models.IntegerField()),
                ('longitud_m', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='inventario.categoria')),
            ],
            options={
                'verbose_name': 'Tubería',
                'verbose_name_plural': 'Tuberías',
            },
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='tuberia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.tuberia'),
        ),
        migrations.AddField(
            model_name='alertastock',
            name='tuberia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.tuberia'),
        ),
        migrations.CreateModel(
            name='StockEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('acueducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_equipo', to='inventario.acueducto')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventario.equipo')),
            ],
            options={
                'verbose_name': 'Stock Equipo',
                'verbose_name_plural': 'Stocks Equipos',
                'unique_together': {('equipo', 'acueducto')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='acueducto',
            unique_together={('nombre', 'sucursal')},
        ),
        migrations.CreateModel(
            name='StockTuberia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('acueducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_tuberia', to='inventario.acueducto')),
                ('tuberia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventario.tuberia')),
            ],
            options={
                'verbose_name': 'Stock Tubería',
                'verbose_name_plural': 'Stocks Tuberías',
                'unique_together': {('tuberia', 'acueducto')},
            },
        ),
    ]
