# Generated by Django 6.0.1 on 2026-01-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_movimientoinventario_inventoryaudit_notificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
