# Generated by Django 6.0.1 on 2026-01-13 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_movimientoinventario_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
            ],
            options={
                'verbose_name': 'Categoría (compat)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventario.category',),
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
            ],
            options={
                'verbose_name': 'Equipo (compat)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventario.pumpandmotor',),
        ),
        migrations.CreateModel(
            name='StockEquipo',
            fields=[
            ],
            options={
                'verbose_name': 'StockEquipo (compat)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventario.stockpumpandmotor',),
        ),
        migrations.CreateModel(
            name='StockTuberia',
            fields=[
            ],
            options={
                'verbose_name': 'StockTubería (compat)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventario.stockpipe',),
        ),
        migrations.CreateModel(
            name='Tuberia',
            fields=[
            ],
            options={
                'verbose_name': 'Tubería (compat)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventario.pipe',),
        ),
    ]
