# Generated by Django 5.0.2 on 2026-02-05 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('geography', '0002_location_refinement_and_stamps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaTecnicaMotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('horas_operacion_totales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado_actual', models.CharField(default='No instalado', max_length=50)),
            ],
            options={
                'verbose_name': 'Ficha Técnica',
                'db_table': 'inventario_fichatecnicamotor',
            },
        ),
        migrations.CreateModel(
            name='MaterialEstrategico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización')),
                ('object_id', models.PositiveIntegerField()),
                ('nivel_criticidad', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto'), ('CRITICO', 'Crítico')], default='MEDIO', max_length=10)),
                ('plan_contingencia', models.TextField(blank=True)),
                ('stock_seguridad_dias', models.IntegerField(default=90)),
                ('requiere_aprobacion_especial', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Material Estratégico',
                'verbose_name_plural': 'Materiales Estratégicos',
                'db_table': 'inventario_materialestrategico',
            },
        ),
        migrations.CreateModel(
            name='RegistroMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_mantenimiento', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('realizado_por', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Registro de Mantenimiento',
                'db_table': 'inventario_registromantenimiento',
            },
        ),
        migrations.CreateModel(
            name='ActivoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización')),
                ('object_id', models.PositiveIntegerField()),
                ('valor_adquisicion', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_adquisicion', models.DateField()),
                ('vida_util_anos', models.IntegerField()),
                ('valor_residual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('codigo_activo', models.CharField(max_length=50, unique=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos_fijos_asignados_new', to=settings.AUTH_USER_MODEL)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos_fijos_new', to='geography.ubicacion')),
            ],
            options={
                'verbose_name': 'Activo Fijo',
                'verbose_name_plural': 'Activos Fijos',
                'db_table': 'inventario_activofijo',
            },
        ),
    ]
