# Generated by Django 5.0.2 on 2026-02-05 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fichatecnicamotor',
            name='equipo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_tecnica_new', to='productos.pumpandmotor'),
        ),
        migrations.AddField(
            model_name='materialestrategico',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='materialestrategico',
            name='proveedor_alternativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales_estrategicos_alternativos', to='productos.supplier'),
        ),
        migrations.AddField(
            model_name='materialestrategico',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiales_estrategicos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registromantenimiento',
            name='ficha_tecnica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='activos.fichatecnicamotor'),
        ),
    ]
