# Generated by Django 5.0.2 on 2026-02-05 20:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registromantenimiento',
            options={'verbose_name': 'Registro de Mantenimiento', 'verbose_name_plural': 'Registros de Mantenimiento'},
        ),
        migrations.AddField(
            model_name='activofijo',
            name='estado_depreciacion',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('EN_USO', 'En Uso'), ('DEPRECIADO', 'Depreciado')], default='EN_USO', max_length=20),
        ),
        migrations.AddField(
            model_name='activofijo',
            name='estado_fisico',
            field=models.CharField(choices=[('EXCELENTE', 'Excelente'), ('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo'), ('FUERA_SERVICIO', 'Fuera de Servicio')], default='BUENO', max_length=20),
        ),
        migrations.AddField(
            model_name='fichatecnicamotor',
            name='clase_aislamiento',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='fichatecnicamotor',
            name='frecuencia_hz',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='fichatecnicamotor',
            name='numero_fases',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='fichatecnicamotor',
            name='potencia_nominal_kw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fichatecnicamotor',
            name='tension_v',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialestrategico',
            name='prioridad_reposicion',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=10),
        ),
        migrations.AddField(
            model_name='registromantenimiento',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registromantenimiento',
            name='prioridad',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=10),
        ),
        migrations.AddField(
            model_name='registromantenimiento',
            name='realizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registromantenimiento',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='registromantenimiento',
            name='tipo_mantenimiento',
            field=models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('CORRECTIVO', 'Correctivo'), ('PREDICTIVO', 'Predictivo')], max_length=50),
        ),
    ]
