# Generated by Django 5.0.2 on 2026-02-05 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0003_alter_registromantenimiento_options_and_more'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialestrategico',
            name='proveedor_alternativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales_estrategicos_alternativos', to='proveedores.supplier'),
        ),
    ]
