# Generated by Django 5.0.2 on 2026-02-06 03:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnaKanban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización')),
                ('nombre', models.CharField(help_text='Nombre de la columna', max_length=50)),
                ('tipo', models.CharField(choices=[('INICIO', 'Estado Inicial'), ('PROGRESO', 'En Progreso'), ('REVISION', 'En Revisión/Bloqueado'), ('FIN', 'Estado Final')], default='PROGRESO', help_text='Tipo de columna', max_length=20)),
                ('color', models.CharField(default='#6B7280', help_text='Color de la columna', max_length=7)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Posición en el tablero')),
                ('limite_tareas', models.PositiveIntegerField(default=0, help_text='Límite máximo de tareas (0 = sin límite)')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Columna Kanban',
                'verbose_name_plural': 'Columnas Kanban',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización')),
                ('nombre', models.CharField(help_text='Nombre de la categoría', max_length=100, unique=True)),
                ('codigo', models.CharField(help_text='Código corto (ej: MANT, ADMIN)', max_length=20, unique=True)),
                ('color', models.CharField(default='#3B82F6', help_text='Color en formato hexadecimal', max_length=7)),
                ('icono', models.CharField(blank=True, default='task', help_text='Nombre del icono (para UI)', max_length=50)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la categoría')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de Tarea',
                'verbose_name_plural': 'Categorías de Tareas',
                'ordering': ['orden', 'nombre'],
                'indexes': [models.Index(fields=['activo'], name='tareas_cate_activo_6ef502_idx'), models.Index(fields=['codigo'], name='tareas_cate_codigo_8a4cea_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización')),
                ('titulo', models.CharField(help_text='Título de la tarea', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En Progreso'), ('EN_REVISION', 'En Revisión'), ('BLOQUEADA', 'Bloqueada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=15)),
                ('fecha_inicio', models.DateTimeField(blank=True, help_text='Fecha de inicio planificada', null=True)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, help_text='Fecha límite', null=True)),
                ('fecha_completada', models.DateTimeField(blank=True, help_text='Fecha en que se completó', null=True)),
                ('porcentaje_completado', models.PositiveIntegerField(default=0, help_text='Porcentaje de avance (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('orden_subtarea', models.PositiveIntegerField(default=0, help_text='Orden dentro de la tarea padre')),
                ('es_recurrente', models.BooleanField(default=False, help_text='Si la tarea se repite automáticamente')),
                ('patron_recurrencia', models.CharField(blank=True, choices=[('DIARIO', 'Diario'), ('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('ANUAL', 'Anual')], help_text='Patrón de repetición', max_length=15)),
                ('intervalo_recurrencia', models.PositiveIntegerField(default=1, help_text='Cada cuántos períodos se repite')),
                ('recurrencia_activa', models.BooleanField(default=True, help_text='Si la recurrencia está activa')),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID de la entidad vinculada', null=True)),
                ('etiquetas', models.CharField(blank=True, help_text='Etiquetas separadas por coma', max_length=500)),
                ('categoria', models.ForeignKey(blank=True, help_text='Categoría de la tarea', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='tareas.categoriatarea')),
                ('columna_kanban', models.ForeignKey(blank=True, help_text='Columna del tablero Kanban', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='tareas.columnakanban')),
                ('content_type', models.ForeignKey(blank=True, help_text='Tipo de entidad vinculada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('creador', models.ForeignKey(help_text='Usuario que creó la tarea', on_delete=django.db.models.deletion.PROTECT, related_name='tareas_creadas', to=settings.AUTH_USER_MODEL)),
                ('tarea_origen', models.ForeignKey(blank=True, help_text='Tarea original que generó esta recurrencia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_generadas', to='tareas.tarea')),
                ('tarea_padre', models.ForeignKey(blank=True, help_text='Tarea principal (si es subtarea)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtareas', to='tareas.tarea')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['-prioridad', 'fecha_vencimiento', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordatorioTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización')),
                ('fecha_recordatorio', models.DateTimeField(help_text='Fecha y hora del recordatorio')),
                ('tipo', models.CharField(choices=[('PUSH', 'Notificación Push'), ('EMAIL', 'Correo Electrónico'), ('TELEGRAM', 'Telegram')], default='PUSH', help_text='Tipo de notificación', max_length=10)),
                ('mensaje', models.CharField(blank=True, help_text='Mensaje personalizado', max_length=255)),
                ('enviado', models.BooleanField(default=False, help_text='Si ya se envió el recordatorio')),
                ('fecha_envio', models.DateTimeField(blank=True, help_text='Fecha en que se envió', null=True)),
                ('usuario', models.ForeignKey(help_text='Usuario a notificar', on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(help_text='Tarea asociada', on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='tareas.tarea')),
            ],
            options={
                'verbose_name': 'Recordatorio',
                'verbose_name_plural': 'Recordatorios',
                'ordering': ['fecha_recordatorio'],
            },
        ),
        migrations.CreateModel(
            name='HistorialTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización')),
                ('accion', models.CharField(choices=[('CREADA', 'Tarea Creada'), ('EDITADA', 'Tarea Editada'), ('ASIGNADA', 'Tarea Asignada'), ('DESASIGNADA', 'Asignación Removida'), ('ESTADO_CAMBIADO', 'Estado Cambiado'), ('PRIORIDAD_CAMBIADA', 'Prioridad Cambiada'), ('FECHA_CAMBIADA', 'Fecha Modificada'), ('COMENTARIO', 'Comentario Agregado'), ('ARCHIVO', 'Archivo Adjuntado'), ('COMPLETADA', 'Tarea Completada'), ('CANCELADA', 'Tarea Cancelada'), ('REABIERTA', 'Tarea Reabierta'), ('RECURRENCIA_GENERADA', 'Recurrencia Generada')], help_text='Tipo de acción', max_length=25)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del cambio')),
                ('datos_anteriores', models.JSONField(blank=True, help_text='Datos antes del cambio', null=True)),
                ('datos_nuevos', models.JSONField(blank=True, help_text='Datos después del cambio', null=True)),
                ('usuario', models.ForeignKey(help_text='Usuario que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_tareas', to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(help_text='Tarea asociada', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='tareas.tarea')),
            ],
            options={
                'verbose_name': 'Historial de Tarea',
                'verbose_name_plural': 'Historial de Tareas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización')),
                ('contenido', models.TextField(help_text='Contenido del comentario')),
                ('autor', models.ForeignKey(help_text='Autor del comentario', on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_tareas', to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(help_text='Tarea comentada', on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tareas.tarea')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización')),
                ('rol', models.CharField(choices=[('RESPONSABLE', 'Responsable'), ('COLABORADOR', 'Colaborador'), ('OBSERVADOR', 'Observador')], default='RESPONSABLE', help_text='Rol en la tarea', max_length=15)),
                ('notificado', models.BooleanField(default=False, help_text='Si el usuario fue notificado')),
                ('asignado_por', models.ForeignKey(help_text='Quién realizó la asignación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(help_text='Usuario asignado', on_delete=django.db.models.deletion.CASCADE, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(help_text='Tarea asignada', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='tareas.tarea')),
            ],
            options={
                'verbose_name': 'Asignación de Tarea',
                'verbose_name_plural': 'Asignaciones de Tareas',
            },
        ),
        migrations.CreateModel(
            name='ArchivoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización')),
                ('archivo', models.FileField(help_text='Archivo', upload_to='tareas/adjuntos/%Y/%m/')),
                ('nombre', models.CharField(help_text='Nombre del archivo', max_length=255)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del archivo')),
                ('subido_por', models.ForeignKey(help_text='Usuario que subió el archivo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos_subidos', to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(help_text='Tarea', on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='tareas.tarea')),
            ],
            options={
                'verbose_name': 'Archivo Adjunto',
                'verbose_name_plural': 'Archivos Adjuntos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['estado'], name='tareas_tare_estado_f62126_idx'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['prioridad'], name='tareas_tare_priorid_87d210_idx'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['fecha_vencimiento'], name='tareas_tare_fecha_v_9a2e07_idx'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['creador'], name='tareas_tare_creador_a548f2_idx'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['es_recurrente'], name='tareas_tare_es_recu_1f454d_idx'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['content_type', 'object_id'], name='tareas_tare_content_b88108_idx'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['tarea_padre'], name='tareas_tare_tarea_p_7db9b2_idx'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['columna_kanban', 'orden_subtarea'], name='tareas_tare_columna_ca7cc8_idx'),
        ),
        migrations.AddIndex(
            model_name='recordatoriotarea',
            index=models.Index(fields=['fecha_recordatorio', 'enviado'], name='tareas_reco_fecha_r_6ad0ad_idx'),
        ),
        migrations.AddIndex(
            model_name='recordatoriotarea',
            index=models.Index(fields=['usuario'], name='tareas_reco_usuario_67b165_idx'),
        ),
        migrations.AddIndex(
            model_name='asignaciontarea',
            index=models.Index(fields=['usuario', 'rol'], name='tareas_asig_usuario_a1ade0_idx'),
        ),
        migrations.AddIndex(
            model_name='asignaciontarea',
            index=models.Index(fields=['tarea'], name='tareas_asig_tarea_i_7c3af4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='asignaciontarea',
            unique_together={('tarea', 'usuario')},
        ),
    ]
