# Generated by Django 5.0.2 on 2026-02-05 15:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaproducto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoriaproducto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización'),
        ),
        migrations.AddField(
            model_name='marca',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marca',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='categoriaproducto',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo se eliminó (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo se eliminó (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización'),
        ),
    ]
