# Generated by Django 5.0.2 on 2026-02-06 03:32

import django.core.validators
import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('rif', models.CharField(blank=True, max_length=30, verbose_name='RIF')),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsidiarias', to='institucion.empresa')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='OrganizacionCentral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('rif', models.CharField(blank=True, max_length=30, verbose_name='RIF')),
                ('parent', models.ForeignKey(blank=True, help_text='Organización superior (ej: MINAGUAS)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_organizaciones', to='institucion.organizacioncentral')),
            ],
            options={
                'verbose_name': 'Organización Central',
                'verbose_name_plural': 'Organizaciones Centrales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('codigo', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('organizacion_central', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sucursales', to='institucion.organizacioncentral')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Subalmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización')),
                ('nombre', models.CharField(help_text='Nombre del subalmacén', max_length=200)),
                ('codigo', models.CharField(help_text='Código único (ej: SUB-ZUL-001)', max_length=20, unique=True)),
                ('direccion', models.TextField(blank=True, help_text='Dirección completa')),
                ('coordenadas_gps', models.CharField(blank=True, help_text='Coordenadas GPS (lat,lng)', max_length=100)),
                ('capacidad', models.IntegerField(blank=True, help_text='Capacidad de almacenamiento', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subalmacenes', to='geography.state')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subalmacenes', to='geography.municipality')),
                ('parroquia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subalmacenes', to='geography.parish')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subalmacenes_responsable', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(help_text='Sucursal a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='subalmacenes', to='institucion.sucursal')),
            ],
            options={
                'verbose_name': 'Subalmacén',
                'verbose_name_plural': 'Subalmacenes',
                'ordering': ['estado__name', 'sucursal__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Acueducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(blank=True, max_length=10)),
                ('ubicacion', models.CharField(blank=True, max_length=255)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acueductos', to='institucion.sucursal')),
            ],
            options={
                'verbose_name': 'Acueducto',
                'verbose_name_plural': 'Acueductos',
                'ordering': ['sucursal', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='UnidadOrganizacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('tipo', models.CharField(choices=[('GERENCIA', 'Gerencia'), ('COORDINACION', 'Coordinación'), ('DEPARTAMENTO', 'Departamento'), ('DIVISION', 'División'), ('SECCION', 'Sección'), ('OFICINA', 'Oficina'), ('ALMACEN', 'Almacén'), ('PLANTA', 'Planta de Tratamiento'), ('ESTACION', 'Estación de Bombeo')], max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_unidades', to='institucion.unidadorganizacional')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unidad Organizacional',
                'verbose_name_plural': 'Unidades Organizacionales',
                'ordering': ['vicepresidencia', 'tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='AlmacenRegional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización')),
                ('nombre', models.CharField(help_text='Nombre del almacén regional', max_length=200)),
                ('prefijo', models.CharField(choices=[('ZUL', 'Zulia'), ('CAR', 'Carabobo'), ('MIR', 'Miranda'), ('ARA', 'Aragua'), ('LAR', 'Lara'), ('TAC', 'Táchira'), ('BOL', 'Bolívar'), ('ANZ', 'Anzoátegui'), ('NVA', 'Nueva Esparta')], help_text='Código único de tres letras para identificar el almacén', max_length=3, unique=True)),
                ('ubicacion', models.CharField(help_text='Ubicación física del almacén', max_length=200)),
                ('capacidad_maxima', models.IntegerField(default=10000, help_text='Capacidad máxima de almacenamiento', validators=[django.core.validators.MinValueValidator(1)])),
                ('activo', models.BooleanField(default=True, help_text='Indica si el almacén está activo')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional del almacén')),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto del almacén', max_length=50)),
                ('email', models.EmailField(blank=True, help_text='Email de contacto del almacén', max_length=254)),
                ('manager', models.ForeignKey(blank=True, help_text='Gerente responsable del almacén', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='almacenes_gestionados', to=settings.AUTH_USER_MODEL)),
                ('unidad_organizacional', models.ForeignKey(help_text='Unidad organizacional bajo VP Operaciones', on_delete=django.db.models.deletion.CASCADE, related_name='almacenes_regionales', to='institucion.unidadorganizacional')),
            ],
            options={
                'verbose_name': 'Almacén Regional',
                'verbose_name_plural': 'Almacenes Regionales',
                'ordering': ['prefijo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vicepresidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('COMERCIALIZACION', 'Vicepresidencia de Comercialización'), ('OPERACIONES_HIDRICAS', 'Vicepresidencia de Operaciones Hídricas'), ('ADMINISTRATIVA', 'Vicepresidencia Administrativa')], max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vicepresidencias', to='institucion.empresa')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_vicepresidencias', to='institucion.vicepresidencia')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vicepresidencias_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vicepresidencia',
                'verbose_name_plural': 'Vicepresidencias',
                'ordering': ['empresa', 'tipo', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='unidadorganizacional',
            name='vicepresidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_organizacionales', to='institucion.vicepresidencia'),
        ),
        migrations.CreateModel(
            name='MigracionOrganizacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizacion_central_id', models.IntegerField(blank=True, help_text='ID of the original OrganizacionCentral record', null=True)),
                ('sucursal_id', models.IntegerField(blank=True, help_text='ID of the original Sucursal record', null=True)),
                ('acueducto_id', models.IntegerField(blank=True, help_text='ID of the original Acueducto record', null=True)),
                ('fecha_migracion', models.DateTimeField(auto_now_add=True, help_text='Timestamp when migration was performed')),
                ('estado_migracion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADA', 'Completada'), ('FALLIDA', 'Fallida'), ('REVERTIDA', 'Revertida')], default='PENDIENTE', help_text='Current migration status', max_length=20)),
                ('validado', models.BooleanField(default=False, help_text='Whether migration has been validated')),
                ('fecha_validacion', models.DateTimeField(blank=True, help_text='Timestamp when migration was validated', null=True)),
                ('datos_originales', models.JSONField(blank=True, default=dict, help_text='Original data snapshot for rollback capability')),
                ('puede_revertir', models.BooleanField(default=True, help_text='Whether this migration can be reverted')),
                ('fecha_reversion', models.DateTimeField(blank=True, help_text='Timestamp when migration was reverted', null=True)),
                ('notas', models.TextField(blank=True, help_text='Additional notes about the migration')),
                ('errores', models.JSONField(blank=True, default=list, help_text='List of errors encountered during migration')),
                ('warnings', models.JSONField(blank=True, default=list, help_text='List of warnings generated during migration')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, help_text='Mapped Empresa in new hierarchy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='migraciones', to='institucion.empresa')),
                ('migrado_por', models.ForeignKey(help_text='User who performed the migration', on_delete=django.db.models.deletion.PROTECT, related_name='migraciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('revertido_por', models.ForeignKey(blank=True, help_text='User who reverted the migration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migraciones_revertidas', to=settings.AUTH_USER_MODEL)),
                ('validado_por', models.ForeignKey(blank=True, help_text='User who validated the migration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migraciones_validadas', to=settings.AUTH_USER_MODEL)),
                ('acueducto_nuevo', models.ForeignKey(blank=True, help_text='Mapped new Subalmacen in new hierarchy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='migraciones', to='institucion.subalmacen')),
                ('unidad_organizacional', models.ForeignKey(blank=True, help_text='Mapped UnidadOrganizacional in new hierarchy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='migraciones', to='institucion.unidadorganizacional')),
                ('vicepresidencia', models.ForeignKey(blank=True, help_text='Mapped Vicepresidencia in new hierarchy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='migraciones', to='institucion.vicepresidencia')),
            ],
            options={
                'verbose_name': 'Migración Organizacional',
                'verbose_name_plural': 'Migraciones Organizacionales',
                'ordering': ['-fecha_migracion'],
            },
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['codigo'], name='institucion_codigo_82e399_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['activo'], name='institucion_activo_1091a6_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['created_at'], name='institucion_created_e5550a_idx'),
        ),
        migrations.AddIndex(
            model_name='subalmacen',
            index=models.Index(fields=['estado', 'activo'], name='institucion_estado__352849_idx'),
        ),
        migrations.AddIndex(
            model_name='subalmacen',
            index=models.Index(fields=['sucursal', 'activo'], name='institucion_sucursa_72699f_idx'),
        ),
        migrations.AddIndex(
            model_name='subalmacen',
            index=models.Index(fields=['codigo'], name='institucion_codigo_d176a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subalmacen',
            unique_together={('nombre', 'sucursal')},
        ),
        migrations.AlterUniqueTogether(
            name='acueducto',
            unique_together={('nombre', 'sucursal')},
        ),
        migrations.AddIndex(
            model_name='almacenregional',
            index=models.Index(fields=['prefijo'], name='institucion_prefijo_505cb9_idx'),
        ),
        migrations.AddIndex(
            model_name='almacenregional',
            index=models.Index(fields=['activo'], name='institucion_activo_7f3e19_idx'),
        ),
        migrations.AddIndex(
            model_name='almacenregional',
            index=models.Index(fields=['unidad_organizacional'], name='institucion_unidad__c374c7_idx'),
        ),
        migrations.AddIndex(
            model_name='almacenregional',
            index=models.Index(fields=['manager'], name='institucion_manager_24621f_idx'),
        ),
        migrations.AddConstraint(
            model_name='almacenregional',
            constraint=models.UniqueConstraint(fields=('prefijo',), name='unique_almacen_prefijo'),
        ),
        migrations.AddIndex(
            model_name='vicepresidencia',
            index=models.Index(fields=['empresa', 'tipo'], name='institucion_empresa_2f7738_idx'),
        ),
        migrations.AddIndex(
            model_name='vicepresidencia',
            index=models.Index(fields=['codigo'], name='institucion_codigo_39e5d8_idx'),
        ),
        migrations.AddIndex(
            model_name='vicepresidencia',
            index=models.Index(fields=['activo'], name='institucion_activo_92860f_idx'),
        ),
        migrations.AddIndex(
            model_name='vicepresidencia',
            index=models.Index(fields=['tipo'], name='institucion_tipo_e34647_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vicepresidencia',
            unique_together={('empresa', 'codigo')},
        ),
        migrations.AddIndex(
            model_name='unidadorganizacional',
            index=models.Index(fields=['vicepresidencia', 'tipo'], name='institucion_vicepre_88c173_idx'),
        ),
        migrations.AddIndex(
            model_name='unidadorganizacional',
            index=models.Index(fields=['codigo'], name='institucion_codigo_76bfe4_idx'),
        ),
        migrations.AddIndex(
            model_name='unidadorganizacional',
            index=models.Index(fields=['activo'], name='institucion_activo_a80d40_idx'),
        ),
        migrations.AddIndex(
            model_name='unidadorganizacional',
            index=models.Index(fields=['tipo'], name='institucion_tipo_d8e353_idx'),
        ),
        migrations.AddIndex(
            model_name='unidadorganizacional',
            index=models.Index(fields=['ubicacion'], name='institucion_ubicaci_8f0386_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unidadorganizacional',
            unique_together={('vicepresidencia', 'codigo')},
        ),
        migrations.AddIndex(
            model_name='migracionorganizacional',
            index=models.Index(fields=['organizacion_central_id'], name='institucion_organiz_66ed00_idx'),
        ),
        migrations.AddIndex(
            model_name='migracionorganizacional',
            index=models.Index(fields=['sucursal_id'], name='institucion_sucursa_eec9f4_idx'),
        ),
        migrations.AddIndex(
            model_name='migracionorganizacional',
            index=models.Index(fields=['acueducto_id'], name='institucion_acueduc_c882c7_idx'),
        ),
        migrations.AddIndex(
            model_name='migracionorganizacional',
            index=models.Index(fields=['estado_migracion'], name='institucion_estado__68ee64_idx'),
        ),
        migrations.AddIndex(
            model_name='migracionorganizacional',
            index=models.Index(fields=['validado'], name='institucion_validad_21d041_idx'),
        ),
        migrations.AddIndex(
            model_name='migracionorganizacional',
            index=models.Index(fields=['fecha_migracion'], name='institucion_fecha_m_0ceaed_idx'),
        ),
        migrations.AddConstraint(
            model_name='migracionorganizacional',
            constraint=models.CheckConstraint(check=models.Q(('organizacion_central_id__isnull', False), ('sucursal_id__isnull', False), ('acueducto_id__isnull', False), _connector='OR'), name='at_least_one_old_reference'),
        ),
    ]
