# Generated by Django 5.0.2 on 2026-01-18 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizacionCentral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('rif', models.CharField(blank=True, max_length=30, verbose_name='RIF')),
            ],
            options={
                'verbose_name': 'Organización Central',
                'verbose_name_plural': 'Organizaciones Centrales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('codigo', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('organizacion_central', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sucursales', to='institucion.organizacioncentral')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Acueducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(blank=True, max_length=10)),
                ('ubicacion', models.CharField(blank=True, max_length=255)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acueductos', to='institucion.sucursal')),
            ],
            options={
                'verbose_name': 'Acueducto',
                'verbose_name_plural': 'Acueductos',
                'ordering': ['sucursal', 'nombre'],
                'unique_together': {('nombre', 'sucursal')},
            },
        ),
    ]
