# Generated by Django 5.0.2 on 2026-01-18 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacioncentral',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Organización superior (ej: MINAGUAS)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_organizaciones', to='institucion.organizacioncentral'),
        ),
    ]
