# Generated by Django 5.0.2 on 2026-02-04 03:51

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0002_organizacioncentral_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('rif', models.CharField(blank=True, max_length=30, verbose_name='RIF')),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsidiarias', to='institucion.empresa')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vicepresidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('COMERCIALIZACION', 'Vicepresidencia de Comercialización'), ('OPERACIONES_HIDRICAS', 'Vicepresidencia de Operaciones Hídricas'), ('ADMINISTRATIVA', 'Vicepresidencia Administrativa')], max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vicepresidencias', to='institucion.empresa')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_vicepresidencias', to='institucion.vicepresidencia')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vicepresidencias_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vicepresidencia',
                'verbose_name_plural': 'Vicepresidencias',
                'ordering': ['empresa', 'tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='UnidadOrganizacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('tipo', models.CharField(choices=[('GERENCIA', 'Gerencia'), ('COORDINACION', 'Coordinación'), ('DEPARTAMENTO', 'Departamento'), ('DIVISION', 'División'), ('SECCION', 'Sección'), ('OFICINA', 'Oficina'), ('ALMACEN', 'Almacén'), ('PLANTA', 'Planta de Tratamiento'), ('ESTACION', 'Estación de Bombeo')], max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_unidades', to='institucion.unidadorganizacional')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_responsable', to=settings.AUTH_USER_MODEL)),
                ('vicepresidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_organizacionales', to='institucion.vicepresidencia')),
            ],
            options={
                'verbose_name': 'Unidad Organizacional',
                'verbose_name_plural': 'Unidades Organizacionales',
                'ordering': ['vicepresidencia', 'tipo', 'nombre'],
            },
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['codigo'], name='institucion_codigo_82e399_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['activo'], name='institucion_activo_1091a6_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['fecha_creacion'], name='institucion_fecha_c_12155b_idx'),
        ),
        migrations.AddIndex(
            model_name='vicepresidencia',
            index=models.Index(fields=['empresa', 'tipo'], name='institucion_empresa_2f7738_idx'),
        ),
        migrations.AddIndex(
            model_name='vicepresidencia',
            index=models.Index(fields=['codigo'], name='institucion_codigo_39e5d8_idx'),
        ),
        migrations.AddIndex(
            model_name='vicepresidencia',
            index=models.Index(fields=['activo'], name='institucion_activo_92860f_idx'),
        ),
        migrations.AddIndex(
            model_name='vicepresidencia',
            index=models.Index(fields=['tipo'], name='institucion_tipo_e34647_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vicepresidencia',
            unique_together={('empresa', 'codigo')},
        ),
        migrations.AddIndex(
            model_name='unidadorganizacional',
            index=models.Index(fields=['vicepresidencia', 'tipo'], name='institucion_vicepre_88c173_idx'),
        ),
        migrations.AddIndex(
            model_name='unidadorganizacional',
            index=models.Index(fields=['codigo'], name='institucion_codigo_76bfe4_idx'),
        ),
        migrations.AddIndex(
            model_name='unidadorganizacional',
            index=models.Index(fields=['activo'], name='institucion_activo_a80d40_idx'),
        ),
        migrations.AddIndex(
            model_name='unidadorganizacional',
            index=models.Index(fields=['tipo'], name='institucion_tipo_d8e353_idx'),
        ),
        migrations.AddIndex(
            model_name='unidadorganizacional',
            index=models.Index(fields=['ubicacion'], name='institucion_ubicaci_8f0386_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unidadorganizacional',
            unique_together={('vicepresidencia', 'codigo')},
        ),
    ]
