# Generated by Django 5.0.2 on 2026-02-04 03:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0003_add_hierarchical_organizational_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlmacenRegional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del almacén regional', max_length=200)),
                ('prefijo', models.CharField(choices=[('ZUL', 'Zulia'), ('CAR', 'Carabobo'), ('MIR', 'Miranda'), ('ARA', 'Aragua'), ('LAR', 'Lara'), ('TAC', 'Táchira'), ('BOL', 'Bolívar'), ('ANZ', 'Anzoátegui'), ('MON', 'Monagas')], help_text='Código único de tres letras para identificar el almacén', max_length=3, unique=True)),
                ('ubicacion', models.CharField(help_text='Ubicación física del almacén', max_length=200)),
                ('capacidad_maxima', models.IntegerField(default=10000, help_text='Capacidad máxima de almacenamiento', validators=[django.core.validators.MinValueValidator(1)])),
                ('activo', models.BooleanField(default=True, help_text='Indica si el almacén está activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional del almacén')),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto del almacén', max_length=50)),
                ('email', models.EmailField(blank=True, help_text='Email de contacto del almacén', max_length=254)),
                ('manager', models.ForeignKey(blank=True, help_text='Gerente responsable del almacén', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='almacenes_gestionados', to=settings.AUTH_USER_MODEL)),
                ('unidad_organizacional', models.ForeignKey(help_text='Unidad organizacional bajo VP Operaciones', on_delete=django.db.models.deletion.CASCADE, related_name='almacenes_regionales', to='institucion.unidadorganizacional')),
            ],
            options={
                'verbose_name': 'Almacén Regional',
                'verbose_name_plural': 'Almacenes Regionales',
                'ordering': ['prefijo', 'nombre'],
                'indexes': [models.Index(fields=['prefijo'], name='institucion_prefijo_505cb9_idx'), models.Index(fields=['activo'], name='institucion_activo_7f3e19_idx'), models.Index(fields=['unidad_organizacional'], name='institucion_unidad__c374c7_idx'), models.Index(fields=['manager'], name='institucion_manager_24621f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='almacenregional',
            constraint=models.UniqueConstraint(fields=('prefijo',), name='unique_almacen_prefijo'),
        ),
    ]
