# Generated by Django 5.0.2 on 2026-02-04 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0004_add_almacen_regional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcueductoNuevo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sistema', models.CharField(choices=[('ACUEDUCTO', 'Acueducto'), ('PLANTA_TRATAMIENTO', 'Planta de Tratamiento'), ('SISTEMA_BOMBEO', 'Sistema de Bombeo'), ('EMBALSE', 'Embalse'), ('POZO', 'Pozo')], default='ACUEDUCTO', help_text='Tipo de sistema de agua', max_length=20)),
                ('nombre', models.CharField(help_text='Nombre del acueducto o sistema', max_length=200)),
                ('codigo', models.CharField(help_text='Código identificador único', max_length=20)),
                ('ubicacion', models.CharField(blank=True, help_text='Ubicación geográfica', max_length=255)),
                ('capacidad_produccion', models.DecimalField(blank=True, decimal_places=2, help_text='Capacidad de producción (litros/segundo)', max_digits=10, null=True)),
                ('poblacion_servida', models.PositiveIntegerField(blank=True, help_text='Población aproximada servida', null=True)),
                ('fecha_inauguracion', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acueductos_nuevos_creados', to=settings.AUTH_USER_MODEL)),
                ('responsable_operativo', models.ForeignKey(help_text='Responsable operativo del acueducto', on_delete=django.db.models.deletion.PROTECT, related_name='acueductos_operados', to=settings.AUTH_USER_MODEL)),
                ('unidad_organizacional', models.ForeignKey(help_text='Unidad organizacional responsable', on_delete=django.db.models.deletion.CASCADE, related_name='acueductos_nuevos', to='institucion.unidadorganizacional')),
            ],
            options={
                'verbose_name': 'Acueducto Nuevo',
                'verbose_name_plural': 'Acueductos Nuevos',
                'ordering': ['unidad_organizacional', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MigracionOrganizacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizacion_central_id', models.IntegerField(blank=True, help_text='ID of the original OrganizacionCentral record', null=True)),
                ('sucursal_id', models.IntegerField(blank=True, help_text='ID of the original Sucursal record', null=True)),
                ('acueducto_id', models.IntegerField(blank=True, help_text='ID of the original Acueducto record', null=True)),
                ('fecha_migracion', models.DateTimeField(auto_now_add=True, help_text='Timestamp when migration was performed')),
                ('estado_migracion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADA', 'Completada'), ('FALLIDA', 'Fallida'), ('REVERTIDA', 'Revertida')], default='PENDIENTE', help_text='Current migration status', max_length=20)),
                ('validado', models.BooleanField(default=False, help_text='Whether migration has been validated')),
                ('fecha_validacion', models.DateTimeField(blank=True, help_text='Timestamp when migration was validated', null=True)),
                ('datos_originales', models.JSONField(blank=True, default=dict, help_text='Original data snapshot for rollback capability')),
                ('puede_revertir', models.BooleanField(default=True, help_text='Whether this migration can be reverted')),
                ('fecha_reversion', models.DateTimeField(blank=True, help_text='Timestamp when migration was reverted', null=True)),
                ('notas', models.TextField(blank=True, help_text='Additional notes about the migration')),
                ('errores', models.JSONField(blank=True, default=list, help_text='List of errors encountered during migration')),
                ('warnings', models.JSONField(blank=True, default=list, help_text='List of warnings generated during migration')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('acueducto_nuevo', models.ForeignKey(blank=True, help_text='Mapped new Acueducto in new hierarchy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='migraciones', to='institucion.acueductonuevo')),
                ('empresa', models.ForeignKey(blank=True, help_text='Mapped Empresa in new hierarchy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='migraciones', to='institucion.empresa')),
                ('migrado_por', models.ForeignKey(help_text='User who performed the migration', on_delete=django.db.models.deletion.PROTECT, related_name='migraciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('revertido_por', models.ForeignKey(blank=True, help_text='User who reverted the migration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migraciones_revertidas', to=settings.AUTH_USER_MODEL)),
                ('unidad_organizacional', models.ForeignKey(blank=True, help_text='Mapped UnidadOrganizacional in new hierarchy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='migraciones', to='institucion.unidadorganizacional')),
                ('validado_por', models.ForeignKey(blank=True, help_text='User who validated the migration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migraciones_validadas', to=settings.AUTH_USER_MODEL)),
                ('vicepresidencia', models.ForeignKey(blank=True, help_text='Mapped Vicepresidencia in new hierarchy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='migraciones', to='institucion.vicepresidencia')),
            ],
            options={
                'verbose_name': 'Migración Organizacional',
                'verbose_name_plural': 'Migraciones Organizacionales',
                'ordering': ['-fecha_migracion'],
            },
        ),
        migrations.AddIndex(
            model_name='acueductonuevo',
            index=models.Index(fields=['codigo'], name='institucion_codigo_868115_idx'),
        ),
        migrations.AddIndex(
            model_name='acueductonuevo',
            index=models.Index(fields=['activo'], name='institucion_activo_791e44_idx'),
        ),
        migrations.AddIndex(
            model_name='acueductonuevo',
            index=models.Index(fields=['tipo_sistema'], name='institucion_tipo_si_902b52_idx'),
        ),
        migrations.AddIndex(
            model_name='acueductonuevo',
            index=models.Index(fields=['unidad_organizacional'], name='institucion_unidad__d335c2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='acueductonuevo',
            unique_together={('unidad_organizacional', 'codigo')},
        ),
        migrations.AddIndex(
            model_name='migracionorganizacional',
            index=models.Index(fields=['organizacion_central_id'], name='institucion_organiz_66ed00_idx'),
        ),
        migrations.AddIndex(
            model_name='migracionorganizacional',
            index=models.Index(fields=['sucursal_id'], name='institucion_sucursa_eec9f4_idx'),
        ),
        migrations.AddIndex(
            model_name='migracionorganizacional',
            index=models.Index(fields=['acueducto_id'], name='institucion_acueduc_c882c7_idx'),
        ),
        migrations.AddIndex(
            model_name='migracionorganizacional',
            index=models.Index(fields=['estado_migracion'], name='institucion_estado__68ee64_idx'),
        ),
        migrations.AddIndex(
            model_name='migracionorganizacional',
            index=models.Index(fields=['validado'], name='institucion_validad_21d041_idx'),
        ),
        migrations.AddIndex(
            model_name='migracionorganizacional',
            index=models.Index(fields=['fecha_migracion'], name='institucion_fecha_m_0ceaed_idx'),
        ),
        migrations.AddConstraint(
            model_name='migracionorganizacional',
            constraint=models.CheckConstraint(check=models.Q(('organizacion_central_id__isnull', False), ('sucursal_id__isnull', False), ('acueducto_id__isnull', False), _connector='OR'), name='at_least_one_old_reference'),
        ),
    ]
