# Generated by Django 5.0.2 on 2026-02-04 04:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('institucion', '0005_acueductonuevo_migracionorganizacional_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_actual', models.CharField(help_text='Código único actual que evoluciona con traslados', max_length=100, unique=True)),
                ('codigo_original', models.CharField(help_text='Código original sin prefijos adicionales de traslados', max_length=100)),
                ('tipo_activo', models.CharField(choices=[('BOMBA', 'Bomba'), ('MOTOR', 'Motor'), ('TUBERIA', 'Tubería'), ('QUIMICO', 'Químico'), ('ACCESORIO', 'Accesorio'), ('EQUIPO', 'Equipo'), ('VALVULA', 'Válvula'), ('MEDIDOR', 'Medidor')], help_text='Tipo de activo para generación de código', max_length=20)),
                ('descripcion', models.TextField(help_text='Descripción detallada del activo')),
                ('estado', models.CharField(choices=[('EN_ALMACEN', 'En Almacén'), ('EN_TRANSITO', 'En Tránsito'), ('INSTALADO', 'Instalado'), ('EN_USO', 'En Uso'), ('MANTENIMIENTO', 'En Mantenimiento')], default='EN_ALMACEN', help_text='Estado actual del activo', max_length=20)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, help_text='Fecha de ingreso al sistema')),
                ('valor_unitario', models.DecimalField(decimal_places=2, help_text='Valor unitario del activo', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('numero_serie', models.CharField(blank=True, help_text='Número de serie del fabricante', max_length=100)),
                ('producto_inventario_id', models.PositiveIntegerField(help_text='ID del producto específico en el inventario')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, help_text='Usuario que actualizó por última vez el activo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activos_actualizados', to=settings.AUTH_USER_MODEL)),
                ('almacen_actual', models.ForeignKey(help_text='Almacén donde se encuentra actualmente', on_delete=django.db.models.deletion.CASCADE, related_name='activos_actuales', to='institucion.almacenregional')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó el registro del activo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activos_creados', to=settings.AUTH_USER_MODEL)),
                ('producto_inventario_type', models.ForeignKey(help_text='Tipo de producto del inventario (ChemicalProduct, Pipe, etc.)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Activo de Inventario',
                'verbose_name_plural': 'Activos de Inventario',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='AprobacionTraslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_aprobacion', models.CharField(choices=[('ORIGEN', 'Origen'), ('DESTINO', 'Destino')], help_text='Tipo de aprobación (origen o destino)', max_length=10)),
                ('decision', models.CharField(choices=[('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], help_text='Decisión tomada', max_length=10)),
                ('fecha_decision', models.DateTimeField(auto_now_add=True, help_text='Fecha de la decisión')),
                ('comentarios', models.TextField(blank=True, help_text='Comentarios sobre la decisión')),
                ('aprobador', models.ForeignKey(help_text='Usuario que realizó la aprobación', on_delete=django.db.models.deletion.CASCADE, related_name='aprobaciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aprobación de Traslado',
                'verbose_name_plural': 'Aprobaciones de Traslado',
                'ordering': ['-fecha_decision'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudTraslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_solicitud', models.CharField(help_text='Número único de la solicitud', max_length=20, unique=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la solicitud')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA_ORIGEN', 'Aprobada por Origen'), ('APROBADA_DESTINO', 'Aprobada por Destino'), ('APROBADA_COMPLETA', 'Completamente Aprobada'), ('EN_TRANSITO', 'En Tránsito'), ('COMPLETADA', 'Completada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', help_text='Estado actual de la solicitud', max_length=20)),
                ('motivo', models.TextField(help_text='Motivo del traslado')),
                ('fecha_limite', models.DateTimeField(help_text='Fecha límite para completar el traslado')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', help_text='Prioridad de la solicitud', max_length=10)),
                ('fecha_ejecucion', models.DateTimeField(blank=True, help_text='Fecha de ejecución del traslado', null=True)),
                ('fecha_completada', models.DateTimeField(blank=True, help_text='Fecha de finalización del traslado', null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales')),
                ('activo', models.ForeignKey(help_text='Activo a trasladar', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_traslado', to='institucion.activoinventario')),
                ('almacen_destino', models.ForeignKey(help_text='Almacén de destino', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_destino', to='institucion.almacenregional')),
                ('almacen_origen', models.ForeignKey(help_text='Almacén de origen', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_origen', to='institucion.almacenregional')),
                ('aprobacion_destino', models.ForeignKey(blank=True, help_text='Aprobación del almacén destino', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_destino', to='institucion.aprobaciontraslado')),
                ('aprobacion_origen', models.ForeignKey(blank=True, help_text='Aprobación del almacén origen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_origen', to='institucion.aprobaciontraslado')),
                ('ejecutado_por', models.ForeignKey(blank=True, help_text='Usuario que ejecutó el traslado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traslados_ejecutados', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(help_text='Usuario que solicita el traslado', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_traslado_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Traslado',
                'verbose_name_plural': 'Solicitudes de Traslado',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='HistorialMovimientoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('INGRESO_INICIAL', 'Ingreso Inicial'), ('TRASLADO_ALMACEN', 'Traslado entre Almacenes'), ('CAMBIO_ESTADO', 'Cambio de Estado'), ('INSTALACION', 'Instalación'), ('RETIRO', 'Retiro'), ('MANTENIMIENTO_ENTRADA', 'Entrada a Mantenimiento'), ('MANTENIMIENTO_SALIDA', 'Salida de Mantenimiento')], help_text='Tipo de movimiento realizado', max_length=30)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del movimiento')),
                ('estado_anterior', models.CharField(choices=[('EN_ALMACEN', 'En Almacén'), ('EN_TRANSITO', 'En Tránsito'), ('INSTALADO', 'Instalado'), ('EN_USO', 'En Uso'), ('MANTENIMIENTO', 'En Mantenimiento')], help_text='Estado anterior del activo', max_length=20)),
                ('estado_nuevo', models.CharField(choices=[('EN_ALMACEN', 'En Almacén'), ('EN_TRANSITO', 'En Tránsito'), ('INSTALADO', 'Instalado'), ('EN_USO', 'En Uso'), ('MANTENIMIENTO', 'En Mantenimiento')], help_text='Estado nuevo del activo', max_length=20)),
                ('codigo_anterior', models.CharField(help_text='Código anterior del activo', max_length=100)),
                ('codigo_nuevo', models.CharField(help_text='Código nuevo del activo', max_length=100)),
                ('motivo', models.TextField(help_text='Motivo del movimiento')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales')),
                ('activo', models.ForeignKey(help_text='Activo al que pertenece este movimiento', on_delete=django.db.models.deletion.CASCADE, related_name='historial_movimientos', to='institucion.activoinventario')),
                ('almacen_destino', models.ForeignKey(blank=True, help_text='Almacén de destino (si aplica)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_destino', to='institucion.almacenregional')),
                ('almacen_origen', models.ForeignKey(blank=True, help_text='Almacén de origen (si aplica)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_origen', to='institucion.almacenregional')),
                ('usuario_responsable', models.ForeignKey(help_text='Usuario responsable del movimiento', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_responsable', to=settings.AUTH_USER_MODEL)),
                ('solicitud_traslado', models.ForeignKey(blank=True, help_text='Solicitud de traslado asociada (si aplica)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_asociados', to='institucion.solicitudtraslado')),
            ],
            options={
                'verbose_name': 'Historial de Movimiento de Activo',
                'verbose_name_plural': 'Historial de Movimientos de Activos',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.AddField(
            model_name='aprobaciontraslado',
            name='solicitud',
            field=models.ForeignKey(help_text='Solicitud de traslado', on_delete=django.db.models.deletion.CASCADE, related_name='aprobaciones', to='institucion.solicitudtraslado'),
        ),
        migrations.AddIndex(
            model_name='activoinventario',
            index=models.Index(fields=['codigo_actual'], name='institucion_codigo__2b2d0e_idx'),
        ),
        migrations.AddIndex(
            model_name='activoinventario',
            index=models.Index(fields=['codigo_original'], name='institucion_codigo__007df1_idx'),
        ),
        migrations.AddIndex(
            model_name='activoinventario',
            index=models.Index(fields=['almacen_actual', 'estado'], name='institucion_almacen_c3fe54_idx'),
        ),
        migrations.AddIndex(
            model_name='activoinventario',
            index=models.Index(fields=['tipo_activo', 'estado'], name='institucion_tipo_ac_c160f7_idx'),
        ),
        migrations.AddIndex(
            model_name='activoinventario',
            index=models.Index(fields=['fecha_ingreso'], name='institucion_fecha_i_f10037_idx'),
        ),
        migrations.AddIndex(
            model_name='activoinventario',
            index=models.Index(fields=['producto_inventario_type', 'producto_inventario_id'], name='institucion_product_d692b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='activoinventario',
            constraint=models.UniqueConstraint(fields=('codigo_actual',), name='unique_activo_codigo_actual'),
        ),
        migrations.AddIndex(
            model_name='solicitudtraslado',
            index=models.Index(fields=['estado', '-fecha_solicitud'], name='institucion_estado_a71eeb_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudtraslado',
            index=models.Index(fields=['almacen_origen', 'estado'], name='institucion_almacen_720b21_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudtraslado',
            index=models.Index(fields=['almacen_destino', 'estado'], name='institucion_almacen_f6e8d7_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudtraslado',
            index=models.Index(fields=['solicitante', '-fecha_solicitud'], name='institucion_solicit_377d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudtraslado',
            index=models.Index(fields=['prioridad', '-fecha_solicitud'], name='institucion_priorid_552c21_idx'),
        ),
        migrations.AddIndex(
            model_name='historialmovimientoactivo',
            index=models.Index(fields=['activo', '-fecha_movimiento'], name='institucion_activo__6bb266_idx'),
        ),
        migrations.AddIndex(
            model_name='historialmovimientoactivo',
            index=models.Index(fields=['almacen_origen', '-fecha_movimiento'], name='institucion_almacen_9e41f6_idx'),
        ),
        migrations.AddIndex(
            model_name='historialmovimientoactivo',
            index=models.Index(fields=['almacen_destino', '-fecha_movimiento'], name='institucion_almacen_e71160_idx'),
        ),
        migrations.AddIndex(
            model_name='historialmovimientoactivo',
            index=models.Index(fields=['tipo_movimiento', '-fecha_movimiento'], name='institucion_tipo_mo_5833e5_idx'),
        ),
        migrations.AddIndex(
            model_name='historialmovimientoactivo',
            index=models.Index(fields=['usuario_responsable', '-fecha_movimiento'], name='institucion_usuario_60e697_idx'),
        ),
        migrations.AddIndex(
            model_name='aprobaciontraslado',
            index=models.Index(fields=['aprobador', '-fecha_decision'], name='institucion_aprobad_37e05f_idx'),
        ),
        migrations.AddIndex(
            model_name='aprobaciontraslado',
            index=models.Index(fields=['decision', '-fecha_decision'], name='institucion_decisio_cf45f9_idx'),
        ),
        migrations.AddIndex(
            model_name='aprobaciontraslado',
            index=models.Index(fields=['solicitud', 'tipo_aprobacion'], name='institucion_solicit_510787_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aprobaciontraslado',
            unique_together={('solicitud', 'tipo_aprobacion')},
        ),
    ]
