# Generated by Django 5.0.2 on 2026-02-04 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0006_add_asset_tracking_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaAccesoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_auditoria', models.DateTimeField(auto_now_add=True, help_text='Timestamp when audit record was created')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, help_text='IP address from which the action was performed', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the request')),
                ('session_key', models.CharField(blank=True, help_text='Session key for tracking user sessions', max_length=40)),
                ('contexto_adicional', models.JSONField(blank=True, default=dict, help_text='Additional context information for the audit record')),
                ('accion', models.CharField(choices=[('LOGIN_SUCCESS', 'Inicio de Sesión Exitoso'), ('LOGIN_FAILED', 'Inicio de Sesión Fallido'), ('LOGOUT', 'Cierre de Sesión'), ('PASSWORD_CHANGE', 'Cambio de Contraseña'), ('PERMISSION_CHECK', 'Verificación de Permisos'), ('UNAUTHORIZED_ACCESS', 'Acceso No Autorizado'), ('SESSION_EXPIRED', 'Sesión Expirada'), ('ACCOUNT_LOCKED', 'Cuenta Bloqueada'), ('ACCOUNT_UNLOCKED', 'Cuenta Desbloqueada'), ('SECURITY_VIOLATION', 'Violación de Seguridad')], help_text='Tipo de evento de acceso', max_length=20)),
                ('recurso_accedido', models.CharField(blank=True, help_text='Recurso o URL accedida', max_length=200)),
                ('metodo_http', models.CharField(blank=True, help_text='Método HTTP utilizado', max_length=10)),
                ('codigo_respuesta', models.IntegerField(blank=True, help_text='Código de respuesta HTTP', null=True)),
                ('exitoso', models.BooleanField(default=True, help_text='Indica si el acceso fue exitoso')),
                ('motivo_fallo', models.TextField(blank=True, help_text='Motivo del fallo de acceso')),
                ('nivel_riesgo', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto'), ('CRITICO', 'Crítico')], default='BAJO', help_text='Nivel de riesgo del evento', max_length=10)),
                ('pais', models.CharField(blank=True, help_text='País desde donde se realizó el acceso', max_length=100)),
                ('ciudad', models.CharField(blank=True, help_text='Ciudad desde donde se realizó el acceso', max_length=100)),
                ('dispositivo', models.CharField(blank=True, help_text='Información del dispositivo utilizado', max_length=200)),
            ],
            options={
                'verbose_name': 'Auditoría de Acceso al Sistema',
                'verbose_name_plural': 'Auditorías de Acceso al Sistema',
                'ordering': ['-fecha_auditoria'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_auditoria', models.DateTimeField(auto_now_add=True, help_text='Timestamp when audit record was created')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, help_text='IP address from which the action was performed', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the request')),
                ('session_key', models.CharField(blank=True, help_text='Session key for tracking user sessions', max_length=40)),
                ('contexto_adicional', models.JSONField(blank=True, default=dict, help_text='Additional context information for the audit record')),
                ('accion', models.CharField(choices=[('APPROVAL_GRANTED', 'Aprobación Otorgada'), ('APPROVAL_REJECTED', 'Aprobación Rechazada'), ('APPROVAL_REVOKED', 'Aprobación Revocada'), ('APPROVAL_DELEGATED', 'Aprobación Delegada'), ('APPROVAL_ESCALATED', 'Aprobación Escalada')], help_text='Tipo de acción de aprobación realizada', max_length=20)),
                ('tipo_aprobacion', models.CharField(choices=[('ORIGEN', 'Origen'), ('DESTINO', 'Destino')], help_text='Tipo de aprobación (origen o destino)', max_length=10)),
                ('decision', models.CharField(choices=[('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], help_text='Decisión tomada', max_length=10)),
                ('comentarios', models.TextField(blank=True, help_text='Comentarios sobre la decisión')),
                ('motivo_rechazo', models.TextField(blank=True, help_text='Motivo detallado del rechazo (si aplica)')),
                ('autoridad_validada', models.BooleanField(default=True, help_text='Indica si la autoridad del aprobador fue validada')),
                ('errores_autoridad', models.JSONField(blank=True, default=list, help_text='Lista de errores de validación de autoridad')),
                ('estado_solicitud_anterior', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA_ORIGEN', 'Aprobada por Origen'), ('APROBADA_DESTINO', 'Aprobada por Destino'), ('APROBADA_COMPLETA', 'Completamente Aprobada'), ('EN_TRANSITO', 'En Tránsito'), ('COMPLETADA', 'Completada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada')], help_text='Estado anterior de la solicitud', max_length=20)),
                ('estado_solicitud_nuevo', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA_ORIGEN', 'Aprobada por Origen'), ('APROBADA_DESTINO', 'Aprobada por Destino'), ('APROBADA_COMPLETA', 'Completamente Aprobada'), ('EN_TRANSITO', 'En Tránsito'), ('COMPLETADA', 'Completada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada')], help_text='Estado nuevo de la solicitud', max_length=20)),
            ],
            options={
                'verbose_name': 'Auditoría de Aprobación',
                'verbose_name_plural': 'Auditorías de Aprobaciones',
                'ordering': ['-fecha_auditoria'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaEstadoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_auditoria', models.DateTimeField(auto_now_add=True, help_text='Timestamp when audit record was created')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, help_text='IP address from which the action was performed', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the request')),
                ('session_key', models.CharField(blank=True, help_text='Session key for tracking user sessions', max_length=40)),
                ('contexto_adicional', models.JSONField(blank=True, default=dict, help_text='Additional context information for the audit record')),
                ('accion', models.CharField(choices=[('STATE_CHANGE', 'Cambio de Estado'), ('STATE_CHANGE_AUTO', 'Cambio de Estado Automático'), ('STATE_VALIDATION', 'Validación de Estado'), ('STATE_CORRECTION', 'Corrección de Estado')], help_text='Tipo de acción realizada', max_length=20)),
                ('estado_anterior', models.CharField(choices=[('EN_ALMACEN', 'En Almacén'), ('EN_TRANSITO', 'En Tránsito'), ('INSTALADO', 'Instalado'), ('EN_USO', 'En Uso'), ('MANTENIMIENTO', 'En Mantenimiento')], help_text='Estado anterior del activo', max_length=20)),
                ('estado_nuevo', models.CharField(choices=[('EN_ALMACEN', 'En Almacén'), ('EN_TRANSITO', 'En Tránsito'), ('INSTALADO', 'Instalado'), ('EN_USO', 'En Uso'), ('MANTENIMIENTO', 'En Mantenimiento')], help_text='Estado nuevo del activo', max_length=20)),
                ('motivo', models.TextField(help_text='Motivo del cambio de estado')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre el cambio')),
                ('validacion_exitosa', models.BooleanField(default=True, help_text='Indica si la validación del cambio fue exitosa')),
                ('errores_validacion', models.JSONField(blank=True, default=list, help_text='Lista de errores de validación si los hubo')),
            ],
            options={
                'verbose_name': 'Auditoría de Estado de Activo',
                'verbose_name_plural': 'Auditorías de Estados de Activos',
                'ordering': ['-fecha_auditoria'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaOperacionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_auditoria', models.DateTimeField(auto_now_add=True, help_text='Timestamp when audit record was created')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, help_text='IP address from which the action was performed', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the request')),
                ('session_key', models.CharField(blank=True, help_text='Session key for tracking user sessions', max_length=40)),
                ('contexto_adicional', models.JSONField(blank=True, default=dict, help_text='Additional context information for the audit record')),
                ('accion', models.CharField(choices=[('SYSTEM_MIGRATION', 'Migración del Sistema'), ('DATA_IMPORT', 'Importación de Datos'), ('DATA_EXPORT', 'Exportación de Datos'), ('BULK_UPDATE', 'Actualización Masiva'), ('SYSTEM_MAINTENANCE', 'Mantenimiento del Sistema'), ('CONFIGURATION_CHANGE', 'Cambio de Configuración'), ('PERMISSION_CHANGE', 'Cambio de Permisos'), ('USER_MANAGEMENT', 'Gestión de Usuarios'), ('WAREHOUSE_MANAGEMENT', 'Gestión de Almacenes'), ('INVENTORY_RECONCILIATION', 'Reconciliación de Inventario')], help_text='Tipo de operación del sistema realizada', max_length=30)),
                ('descripcion', models.TextField(help_text='Descripción detallada de la operación')),
                ('entidades_afectadas', models.JSONField(default=list, help_text='Lista de entidades afectadas por la operación')),
                ('parametros_operacion', models.JSONField(default=dict, help_text='Parámetros utilizados en la operación')),
                ('exitosa', models.BooleanField(default=True, help_text='Indica si la operación fue exitosa')),
                ('errores', models.JSONField(blank=True, default=list, help_text='Lista de errores ocurridos durante la operación')),
                ('warnings', models.JSONField(blank=True, default=list, help_text='Lista de advertencias generadas durante la operación')),
                ('duracion_segundos', models.DecimalField(blank=True, decimal_places=3, help_text='Duración de la operación en segundos', max_digits=10, null=True)),
                ('registros_procesados', models.IntegerField(blank=True, help_text='Número de registros procesados', null=True)),
                ('puede_revertir', models.BooleanField(default=False, help_text='Indica si la operación puede ser revertida')),
                ('datos_rollback', models.JSONField(blank=True, default=dict, help_text='Datos necesarios para revertir la operación')),
            ],
            options={
                'verbose_name': 'Auditoría de Operación del Sistema',
                'verbose_name_plural': 'Auditorías de Operaciones del Sistema',
                'ordering': ['-fecha_auditoria'],
            },
        ),
        migrations.AddField(
            model_name='historialmovimientoactivo',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata for the movement operation'),
        ),
        migrations.AlterField(
            model_name='historialmovimientoactivo',
            name='tipo_movimiento',
            field=models.CharField(choices=[('INGRESO_INICIAL', 'Ingreso Inicial'), ('TRASLADO_ALMACEN', 'Traslado entre Almacenes'), ('TRASLADO_EJECUTADO', 'Traslado Ejecutado'), ('ROLLBACK_TRASLADO', 'Rollback de Traslado'), ('CAMBIO_ESTADO', 'Cambio de Estado'), ('CAMBIO_ESTADO_AUTO_TRANSFER_APPROVED', 'Cambio de Estado Automático - Traslado Aprobado'), ('CAMBIO_ESTADO_AUTO_TRANSFER_COMPLETED', 'Cambio de Estado Automático - Traslado Completado'), ('CAMBIO_ESTADO_AUTO_MAINTENANCE_REQUIRED', 'Cambio de Estado Automático - Mantenimiento Requerido'), ('INSTALACION', 'Instalación'), ('RETIRO', 'Retiro'), ('MANTENIMIENTO_ENTRADA', 'Entrada a Mantenimiento'), ('MANTENIMIENTO_SALIDA', 'Salida de Mantenimiento')], help_text='Tipo de movimiento realizado', max_length=50),
        ),
        migrations.AddIndex(
            model_name='aprobaciontraslado',
            index=models.Index(fields=['aprobador', 'decision', '-fecha_decision'], name='institucion_aprobad_20fff2_idx'),
        ),
        migrations.AddIndex(
            model_name='aprobaciontraslado',
            index=models.Index(fields=['tipo_aprobacion', 'decision', '-fecha_decision'], name='institucion_tipo_ap_4b11a0_idx'),
        ),
        migrations.AddIndex(
            model_name='aprobaciontraslado',
            index=models.Index(fields=['solicitud', 'decision'], name='institucion_solicit_2ca2bc_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudtraslado',
            index=models.Index(fields=['almacen_origen', 'estado', '-fecha_solicitud'], name='institucion_almacen_c9ec7d_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudtraslado',
            index=models.Index(fields=['almacen_destino', 'estado', '-fecha_solicitud'], name='institucion_almacen_78e4bc_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudtraslado',
            index=models.Index(fields=['fecha_limite', 'estado'], name='institucion_fecha_l_fae04b_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudtraslado',
            index=models.Index(fields=['prioridad', 'estado', '-fecha_solicitud'], name='institucion_priorid_84c2d4_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudtraslado',
            index=models.Index(fields=['aprobacion_origen', 'estado'], name='institucion_aprobac_201b95_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudtraslado',
            index=models.Index(fields=['aprobacion_destino', 'estado'], name='institucion_aprobac_fa9406_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudtraslado',
            index=models.Index(fields=['estado', 'fecha_limite'], name='institucion_estado_e70052_idx'),
        ),
        migrations.AddField(
            model_name='auditoriaaccesosistema',
            name='usuario_objetivo',
            field=models.ForeignKey(blank=True, help_text='Usuario objetivo del evento (puede ser diferente al responsable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditoria_acceso_objetivo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditoriaaccesosistema',
            name='usuario_responsable',
            field=models.ForeignKey(help_text='User responsible for the audited action', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_audit_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditoriaaprobacion',
            name='aprobacion',
            field=models.ForeignKey(blank=True, help_text='Registro de aprobación relacionado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditoria_records', to='institucion.aprobaciontraslado'),
        ),
        migrations.AddField(
            model_name='auditoriaaprobacion',
            name='solicitud_traslado',
            field=models.ForeignKey(help_text='Solicitud de traslado relacionada', on_delete=django.db.models.deletion.CASCADE, related_name='auditoria_aprobaciones', to='institucion.solicitudtraslado'),
        ),
        migrations.AddField(
            model_name='auditoriaaprobacion',
            name='usuario_responsable',
            field=models.ForeignKey(help_text='User responsible for the audited action', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_audit_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditoriaestadoactivo',
            name='activo',
            field=models.ForeignKey(help_text='Activo cuyo estado fue modificado', on_delete=django.db.models.deletion.CASCADE, related_name='auditoria_estados', to='institucion.activoinventario'),
        ),
        migrations.AddField(
            model_name='auditoriaestadoactivo',
            name='solicitud_traslado',
            field=models.ForeignKey(blank=True, help_text='Solicitud de traslado relacionada (si aplica)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditoria_estados', to='institucion.solicitudtraslado'),
        ),
        migrations.AddField(
            model_name='auditoriaestadoactivo',
            name='usuario_responsable',
            field=models.ForeignKey(help_text='User responsible for the audited action', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_audit_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditoriaoperacionsistema',
            name='usuario_responsable',
            field=models.ForeignKey(help_text='User responsible for the audited action', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_audit_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditoriaaccesosistema',
            index=models.Index(fields=['accion', '-fecha_auditoria'], name='institucion_accion_e6520d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaccesosistema',
            index=models.Index(fields=['usuario_responsable', '-fecha_auditoria'], name='institucion_usuario_3c9e09_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaccesosistema',
            index=models.Index(fields=['usuario_objetivo', '-fecha_auditoria'], name='institucion_usuario_75edfc_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaccesosistema',
            index=models.Index(fields=['exitoso', '-fecha_auditoria'], name='institucion_exitoso_34bf1a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaccesosistema',
            index=models.Index(fields=['nivel_riesgo', '-fecha_auditoria'], name='institucion_nivel_r_66e713_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaccesosistema',
            index=models.Index(fields=['direccion_ip', '-fecha_auditoria'], name='institucion_direcci_0bc029_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaprobacion',
            index=models.Index(fields=['solicitud_traslado', '-fecha_auditoria'], name='institucion_solicit_30efd3_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaprobacion',
            index=models.Index(fields=['accion', '-fecha_auditoria'], name='institucion_accion_2caff7_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaprobacion',
            index=models.Index(fields=['usuario_responsable', '-fecha_auditoria'], name='institucion_usuario_04ea39_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaprobacion',
            index=models.Index(fields=['decision', '-fecha_auditoria'], name='institucion_decisio_dae755_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaprobacion',
            index=models.Index(fields=['tipo_aprobacion', 'decision'], name='institucion_tipo_ap_1b7b60_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaprobacion',
            index=models.Index(fields=['autoridad_validada', '-fecha_auditoria'], name='institucion_autorid_a8b31b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaestadoactivo',
            index=models.Index(fields=['activo', '-fecha_auditoria'], name='institucion_activo__df3249_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaestadoactivo',
            index=models.Index(fields=['accion', '-fecha_auditoria'], name='institucion_accion_7c8d53_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaestadoactivo',
            index=models.Index(fields=['usuario_responsable', '-fecha_auditoria'], name='institucion_usuario_29a850_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaestadoactivo',
            index=models.Index(fields=['estado_anterior', 'estado_nuevo'], name='institucion_estado__c75ed0_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaestadoactivo',
            index=models.Index(fields=['validacion_exitosa', '-fecha_auditoria'], name='institucion_validac_77b75c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaoperacionsistema',
            index=models.Index(fields=['accion', '-fecha_auditoria'], name='institucion_accion_d44f7c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaoperacionsistema',
            index=models.Index(fields=['usuario_responsable', '-fecha_auditoria'], name='institucion_usuario_0f52af_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaoperacionsistema',
            index=models.Index(fields=['exitosa', '-fecha_auditoria'], name='institucion_exitosa_0798bf_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaoperacionsistema',
            index=models.Index(fields=['puede_revertir', '-fecha_auditoria'], name='institucion_puede_r_d22e17_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaoperacionsistema',
            index=models.Index(fields=['duracion_segundos'], name='institucion_duracio_a599dc_idx'),
        ),
    ]
