# Generated by Django 5.0.2 on 2026-02-04 09:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0007_add_comprehensive_audit_trail_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditoriaaccesosistema',
            new_name='idx_aud_acc_accion_fecha',
            old_name='institucion_accion_e6520d_idx',
        ),
        migrations.RenameIndex(
            model_name='auditoriaaccesosistema',
            new_name='idx_aud_acc_usuario_fecha',
            old_name='institucion_usuario_3c9e09_idx',
        ),
        migrations.RenameIndex(
            model_name='auditoriaaccesosistema',
            new_name='idx_aud_acc_objetivo_fecha',
            old_name='institucion_usuario_75edfc_idx',
        ),
        migrations.RenameIndex(
            model_name='auditoriaaccesosistema',
            new_name='idx_aud_acc_exitoso_fecha',
            old_name='institucion_exitoso_34bf1a_idx',
        ),
        migrations.RenameIndex(
            model_name='auditoriaaccesosistema',
            new_name='idx_aud_acc_riesgo_fecha',
            old_name='institucion_nivel_r_66e713_idx',
        ),
        migrations.RenameIndex(
            model_name='auditoriaaccesosistema',
            new_name='idx_aud_acc_ip_fecha',
            old_name='institucion_direcci_0bc029_idx',
        ),
        migrations.RenameIndex(
            model_name='auditoriaaprobacion',
            new_name='idx_aud_apr_sol_fecha',
            old_name='institucion_solicit_30efd3_idx',
        ),
        migrations.RenameIndex(
            model_name='auditoriaaprobacion',
            new_name='idx_aud_apr_accion_fecha',
            old_name='institucion_accion_2caff7_idx',
        ),
        migrations.RenameIndex(
            model_name='auditoriaaprobacion',
            new_name='idx_aud_apr_usuario_fecha',
            old_name='institucion_usuario_04ea39_idx',
        ),
        migrations.RenameIndex(
            model_name='auditoriaaprobacion',
            new_name='idx_aud_apr_decision_fecha',
            old_name='institucion_decisio_dae755_idx',
        ),
        migrations.RenameIndex(
            model_name='auditoriaaprobacion',
            new_name='idx_aud_apr_tipo_decision',
            old_name='institucion_tipo_ap_1b7b60_idx',
        ),
        migrations.RenameIndex(
            model_name='auditoriaaprobacion',
            new_name='idx_aud_apr_autor_fecha',
            old_name='institucion_autorid_a8b31b_idx',
        ),
        migrations.RenameIndex(
            model_name='auditoriaestadoactivo',
            new_name='idx_aud_est_activo_fecha',
            old_name='institucion_activo__df3249_idx',
        ),
        migrations.RenameIndex(
            model_name='auditoriaestadoactivo',
            new_name='idx_aud_est_accion_fecha',
            old_name='institucion_accion_7c8d53_idx',
        ),
        migrations.RenameIndex(
            model_name='auditoriaestadoactivo',
            new_name='idx_aud_est_usuario_fecha',
            old_name='institucion_usuario_29a850_idx',
        ),
        migrations.RenameIndex(
            model_name='auditoriaestadoactivo',
            new_name='idx_aud_est_transicion',
            old_name='institucion_estado__c75ed0_idx',
        ),
        migrations.RenameIndex(
            model_name='auditoriaestadoactivo',
            new_name='idx_aud_est_valid_fecha',
            old_name='institucion_validac_77b75c_idx',
        ),
        migrations.RenameIndex(
            model_name='auditoriaoperacionsistema',
            new_name='idx_aud_oper_accion_fecha',
            old_name='institucion_accion_d44f7c_idx',
        ),
        migrations.RenameIndex(
            model_name='auditoriaoperacionsistema',
            new_name='idx_aud_oper_usuario_fecha',
            old_name='institucion_usuario_0f52af_idx',
        ),
        migrations.RenameIndex(
            model_name='auditoriaoperacionsistema',
            new_name='idx_aud_oper_exitosa_fecha',
            old_name='institucion_exitosa_0798bf_idx',
        ),
        migrations.RenameIndex(
            model_name='auditoriaoperacionsistema',
            new_name='idx_aud_oper_revert_fecha',
            old_name='institucion_puede_r_d22e17_idx',
        ),
        migrations.RenameIndex(
            model_name='auditoriaoperacionsistema',
            new_name='idx_aud_oper_duracion',
            old_name='institucion_duracio_a599dc_idx',
        ),
        migrations.RenameIndex(
            model_name='historialmovimientoactivo',
            new_name='idx_hist_activo_fecha',
            old_name='institucion_activo__6bb266_idx',
        ),
        migrations.RenameIndex(
            model_name='historialmovimientoactivo',
            new_name='idx_hist_origen_fecha',
            old_name='institucion_almacen_9e41f6_idx',
        ),
        migrations.RenameIndex(
            model_name='historialmovimientoactivo',
            new_name='idx_hist_destino_fecha',
            old_name='institucion_almacen_e71160_idx',
        ),
        migrations.RenameIndex(
            model_name='historialmovimientoactivo',
            new_name='idx_hist_tipo_fecha',
            old_name='institucion_tipo_mo_5833e5_idx',
        ),
        migrations.RenameIndex(
            model_name='historialmovimientoactivo',
            new_name='idx_hist_usuario_fecha',
            old_name='institucion_usuario_60e697_idx',
        ),
        migrations.AddField(
            model_name='auditoriaaccesosistema',
            name='checksum',
            field=models.CharField(blank=True, help_text='SHA-256 checksum for audit record integrity verification', max_length=64),
        ),
        migrations.AddField(
            model_name='auditoriaaccesosistema',
            name='request_method',
            field=models.CharField(blank=True, help_text='HTTP method used for the request', max_length=10),
        ),
        migrations.AddField(
            model_name='auditoriaaccesosistema',
            name='request_path',
            field=models.CharField(blank=True, help_text='Request path/URL', max_length=500),
        ),
        migrations.AddField(
            model_name='auditoriaaprobacion',
            name='checksum',
            field=models.CharField(blank=True, help_text='SHA-256 checksum for audit record integrity verification', max_length=64),
        ),
        migrations.AddField(
            model_name='auditoriaaprobacion',
            name='request_method',
            field=models.CharField(blank=True, help_text='HTTP method used for the request', max_length=10),
        ),
        migrations.AddField(
            model_name='auditoriaaprobacion',
            name='request_path',
            field=models.CharField(blank=True, help_text='Request path/URL', max_length=500),
        ),
        migrations.AddField(
            model_name='auditoriaestadoactivo',
            name='checksum',
            field=models.CharField(blank=True, help_text='SHA-256 checksum for audit record integrity verification', max_length=64),
        ),
        migrations.AddField(
            model_name='auditoriaestadoactivo',
            name='request_method',
            field=models.CharField(blank=True, help_text='HTTP method used for the request', max_length=10),
        ),
        migrations.AddField(
            model_name='auditoriaestadoactivo',
            name='request_path',
            field=models.CharField(blank=True, help_text='Request path/URL', max_length=500),
        ),
        migrations.AddField(
            model_name='auditoriaoperacionsistema',
            name='checksum',
            field=models.CharField(blank=True, help_text='SHA-256 checksum for audit record integrity verification', max_length=64),
        ),
        migrations.AddField(
            model_name='auditoriaoperacionsistema',
            name='request_method',
            field=models.CharField(blank=True, help_text='HTTP method used for the request', max_length=10),
        ),
        migrations.AddField(
            model_name='auditoriaoperacionsistema',
            name='request_path',
            field=models.CharField(blank=True, help_text='Request path/URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='auditoriaaccesosistema',
            name='direccion_ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, help_text='IP address from which the action was performed', null=True),
        ),
        migrations.AlterField(
            model_name='auditoriaaccesosistema',
            name='fecha_auditoria',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when audit record was created (immutable)'),
        ),
        migrations.AlterField(
            model_name='auditoriaaccesosistema',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, help_text='Session key for tracking user sessions', max_length=40),
        ),
        migrations.AlterField(
            model_name='auditoriaaprobacion',
            name='direccion_ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, help_text='IP address from which the action was performed', null=True),
        ),
        migrations.AlterField(
            model_name='auditoriaaprobacion',
            name='fecha_auditoria',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when audit record was created (immutable)'),
        ),
        migrations.AlterField(
            model_name='auditoriaaprobacion',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, help_text='Session key for tracking user sessions', max_length=40),
        ),
        migrations.AlterField(
            model_name='auditoriaestadoactivo',
            name='direccion_ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, help_text='IP address from which the action was performed', null=True),
        ),
        migrations.AlterField(
            model_name='auditoriaestadoactivo',
            name='fecha_auditoria',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when audit record was created (immutable)'),
        ),
        migrations.AlterField(
            model_name='auditoriaestadoactivo',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, help_text='Session key for tracking user sessions', max_length=40),
        ),
        migrations.AlterField(
            model_name='auditoriaoperacionsistema',
            name='direccion_ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, help_text='IP address from which the action was performed', null=True),
        ),
        migrations.AlterField(
            model_name='auditoriaoperacionsistema',
            name='fecha_auditoria',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when audit record was created (immutable)'),
        ),
        migrations.AlterField(
            model_name='auditoriaoperacionsistema',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, help_text='Session key for tracking user sessions', max_length=40),
        ),
        migrations.AlterField(
            model_name='historialmovimientoactivo',
            name='tipo_movimiento',
            field=models.CharField(choices=[('INGRESO_INICIAL', 'Ingreso Inicial'), ('TRASLADO_ALMACEN', 'Traslado entre Almacenes'), ('TRASLADO_EJECUTADO', 'Traslado Ejecutado'), ('ROLLBACK_TRASLADO', 'Rollback de Traslado'), ('CAMBIO_ESTADO', 'Cambio de Estado'), ('CAMBIO_ESTADO_AUTO_TRANSFER_APPROVED', 'Cambio de Estado Automático - Traslado Aprobado'), ('CAMBIO_ESTADO_AUTO_TRANSFER_COMPLETED', 'Cambio de Estado Automático - Traslado Completado'), ('CAMBIO_ESTADO_AUTO_MAINTENANCE_REQUIRED', 'Cambio de Estado Automático - Mantenimiento Requerido'), ('INSTALACION', 'Instalación'), ('RETIRO', 'Retiro'), ('MANTENIMIENTO_ENTRADA', 'Entrada a Mantenimiento'), ('MANTENIMIENTO_SALIDA', 'Salida de Mantenimiento'), ('CORRECCION_INVENTARIO', 'Corrección de Inventario'), ('AUDITORIA_FISICA', 'Auditoría Física'), ('BAJA_ACTIVO', 'Baja de Activo'), ('REACTIVACION_ACTIVO', 'Reactivación de Activo')], help_text='Tipo de movimiento realizado', max_length=50),
        ),
        migrations.AddIndex(
            model_name='auditoriaaccesosistema',
            index=models.Index(fields=['exitoso', 'accion', '-fecha_auditoria'], name='idx_aud_acc_exit_acc_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaccesosistema',
            index=models.Index(fields=['exitoso', 'direccion_ip', '-fecha_auditoria'], name='idx_aud_acc_exit_ip_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaccesosistema',
            index=models.Index(fields=['nivel_riesgo', 'exitoso', '-fecha_auditoria'], name='idx_aud_acc_risk_exit_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaccesosistema',
            index=models.Index(fields=['pais', '-fecha_auditoria'], name='idx_aud_acc_pais_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaccesosistema',
            index=models.Index(fields=['ciudad', '-fecha_auditoria'], name='idx_aud_acc_ciudad_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaccesosistema',
            index=models.Index(fields=['usuario_responsable', 'exitoso', '-fecha_auditoria'], name='idx_aud_acc_usr_exit_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaccesosistema',
            index=models.Index(fields=['accion', 'nivel_riesgo', '-fecha_auditoria'], name='idx_aud_acc_acc_risk_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaccesosistema',
            index=models.Index(fields=['direccion_ip', 'exitoso', '-fecha_auditoria'], name='idx_aud_acc_ip_exit_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaccesosistema',
            index=models.Index(fields=['recurso_accedido', '-fecha_auditoria'], name='idx_aud_acc_recurso_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaccesosistema',
            index=models.Index(fields=['metodo_http', 'codigo_respuesta', '-fecha_auditoria'], name='idx_aud_acc_http_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaprobacion',
            index=models.Index(fields=['tipo_aprobacion', 'decision', '-fecha_auditoria'], name='idx_aud_apr_tip_dec_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaprobacion',
            index=models.Index(fields=['estado_solicitud_anterior', 'estado_solicitud_nuevo'], name='idx_aud_apr_estados'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaprobacion',
            index=models.Index(fields=['estado_solicitud_nuevo', '-fecha_auditoria'], name='idx_aud_apr_est_new_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaprobacion',
            index=models.Index(fields=['accion', 'autoridad_validada', '-fecha_auditoria'], name='idx_aud_apr_acc_aut_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaprobacion',
            index=models.Index(fields=['usuario_responsable', 'decision', '-fecha_auditoria'], name='idx_aud_apr_usr_dec_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaprobacion',
            index=models.Index(fields=['solicitud_traslado', 'tipo_aprobacion', '-fecha_auditoria'], name='idx_aud_apr_sol_tip_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaprobacion',
            index=models.Index(fields=['aprobacion', '-fecha_auditoria'], name='idx_aud_apr_aprob_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaprobacion',
            index=models.Index(fields=['decision', 'autoridad_validada', '-fecha_auditoria'], name='idx_aud_apr_dec_aut_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaestadoactivo',
            index=models.Index(fields=['estado_anterior', 'estado_nuevo', '-fecha_auditoria'], name='idx_aud_est_trans_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaestadoactivo',
            index=models.Index(fields=['activo', 'accion', '-fecha_auditoria'], name='idx_aud_est_act_acc_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaestadoactivo',
            index=models.Index(fields=['activo', 'estado_nuevo', '-fecha_auditoria'], name='idx_aud_est_act_new_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaestadoactivo',
            index=models.Index(fields=['solicitud_traslado', '-fecha_auditoria'], name='idx_aud_est_sol_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaestadoactivo',
            index=models.Index(fields=['accion', 'validacion_exitosa', '-fecha_auditoria'], name='idx_aud_est_acc_val_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaestadoactivo',
            index=models.Index(fields=['usuario_responsable', 'accion', '-fecha_auditoria'], name='idx_aud_est_usr_acc_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaoperacionsistema',
            index=models.Index(fields=['registros_procesados'], name='idx_aud_oper_registros'),
        ),
        migrations.AddIndex(
            model_name='auditoriaoperacionsistema',
            index=models.Index(fields=['accion', 'exitosa', '-fecha_auditoria'], name='idx_aud_oper_acc_exit_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaoperacionsistema',
            index=models.Index(fields=['usuario_responsable', 'accion', '-fecha_auditoria'], name='idx_aud_oper_usr_acc_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaoperacionsistema',
            index=models.Index(fields=['exitosa', 'puede_revertir', '-fecha_auditoria'], name='idx_aud_oper_exit_rev_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaoperacionsistema',
            index=models.Index(fields=['accion', 'duracion_segundos', '-fecha_auditoria'], name='idx_aud_oper_acc_dur_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaoperacionsistema',
            index=models.Index(fields=['registros_procesados', '-fecha_auditoria'], name='idx_aud_oper_reg_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaoperacionsistema',
            index=models.Index(fields=['exitosa', 'accion', '-fecha_auditoria'], name='idx_aud_oper_exit_acc_fecha'),
        ),
        migrations.AddIndex(
            model_name='historialmovimientoactivo',
            index=models.Index(fields=['activo', 'tipo_movimiento', '-fecha_movimiento'], name='idx_hist_activo_tipo_fecha'),
        ),
        migrations.AddIndex(
            model_name='historialmovimientoactivo',
            index=models.Index(fields=['almacen_origen', 'almacen_destino', '-fecha_movimiento'], name='idx_hist_orig_dest_fecha'),
        ),
        migrations.AddIndex(
            model_name='historialmovimientoactivo',
            index=models.Index(fields=['estado_anterior', 'estado_nuevo', '-fecha_movimiento'], name='idx_hist_estados_fecha'),
        ),
        migrations.AddIndex(
            model_name='historialmovimientoactivo',
            index=models.Index(fields=['fecha_movimiento'], name='idx_hist_fecha_only'),
        ),
        migrations.AddIndex(
            model_name='historialmovimientoactivo',
            index=models.Index(fields=['solicitud_traslado', '-fecha_movimiento'], name='idx_hist_solicitud_fecha'),
        ),
        migrations.AddIndex(
            model_name='historialmovimientoactivo',
            index=models.Index(fields=['activo', 'almacen_origen', '-fecha_movimiento'], name='idx_hist_act_orig_fecha'),
        ),
        migrations.AddIndex(
            model_name='historialmovimientoactivo',
            index=models.Index(fields=['activo', 'almacen_destino', '-fecha_movimiento'], name='idx_hist_act_dest_fecha'),
        ),
        migrations.AddIndex(
            model_name='historialmovimientoactivo',
            index=models.Index(fields=['tipo_movimiento', 'estado_nuevo', '-fecha_movimiento'], name='idx_hist_tipo_est_fecha'),
        ),
        migrations.AddConstraint(
            model_name='auditoriaaccesosistema',
            constraint=models.CheckConstraint(check=models.Q(('codigo_respuesta__isnull', True), models.Q(('codigo_respuesta__gte', 100), ('codigo_respuesta__lt', 600)), _connector='OR'), name='audit_acceso_codigo_respuesta_valid'),
        ),
        migrations.AddConstraint(
            model_name='auditoriaestadoactivo',
            constraint=models.CheckConstraint(check=models.Q(('estado_anterior', models.F('estado_nuevo')), _negated=True), name='audit_estado_different_states'),
        ),
        migrations.AddConstraint(
            model_name='auditoriaoperacionsistema',
            constraint=models.CheckConstraint(check=models.Q(('duracion_segundos__isnull', True), ('duracion_segundos__gte', 0), _connector='OR'), name='audit_oper_duracion_positive'),
        ),
        migrations.AddConstraint(
            model_name='auditoriaoperacionsistema',
            constraint=models.CheckConstraint(check=models.Q(('registros_procesados__isnull', True), ('registros_procesados__gte', 0), _connector='OR'), name='audit_oper_registros_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='historialmovimientoactivo',
            constraint=models.CheckConstraint(check=models.Q(('fecha_movimiento__isnull', False)), name='historial_fecha_movimiento_required'),
        ),
    ]
