# Generated by Django 5.0.2 on 2026-02-04 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0002_add_subalmacen_and_qr'),
        ('institucion', '0008_rename_institucion_accion_e6520d_idx_idx_aud_acc_accion_fecha_and_more'),
    ]

    operations = [
    ]
