# Generated by Django 5.0.2 on 2026-02-05 19:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0009_merge_20260204_1856'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='empresa',
            name='institucion_fecha_c_12155b_idx',
        ),
        migrations.RenameIndex(
            model_name='subalmacen',
            new_name='institucion_estado__352849_idx',
            old_name='institucion_estado_activo_idx',
        ),
        migrations.RenameIndex(
            model_name='subalmacen',
            new_name='institucion_sucursa_72699f_idx',
            old_name='institucion_sucursal_activo_idx',
        ),
        migrations.RenameIndex(
            model_name='subalmacen',
            new_name='institucion_codigo_d176a8_idx',
            old_name='institucion_codigo_idx',
        ),
        migrations.RemoveField(
            model_name='almacenregional',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='almacenregional',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='unidadorganizacional',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='unidadorganizacional',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='vicepresidencia',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='vicepresidencia',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='almacenregional',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='almacenregional',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización'),
        ),
        migrations.AddField(
            model_name='unidadorganizacional',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidadorganizacional',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización'),
        ),
        migrations.AddField(
            model_name='vicepresidencia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vicepresidencia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='almacenregional',
            name='prefijo',
            field=models.CharField(choices=[('ZUL', 'Zulia'), ('CAR', 'Carabobo'), ('MIR', 'Miranda'), ('ARA', 'Aragua'), ('LAR', 'Lara'), ('TAC', 'Táchira'), ('BOL', 'Bolívar'), ('ANZ', 'Anzoátegui'), ('NVA', 'Nueva Esparta')], help_text='Código único de tres letras para identificar el almacén', max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='subalmacen',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='subalmacen',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['created_at'], name='institucion_created_e5550a_idx'),
        ),
    ]
