# Generated by Django 5.0.2 on 2026-02-05 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
        ('institucion', '0010_location_refinement_and_stamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='almacen_regional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubicaciones', to='institucion.almacenregional'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='subalmacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubicaciones', to='institucion.subalmacen'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='acueducto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubicaciones', to='institucion.acueducto'),
        ),
    ]
