# Generated by Django 5.0.2 on 2026-02-06 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='acueducto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubicaciones', to='institucion.acueducto'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='almacen_regional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubicaciones', to='institucion.almacenregional'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='parish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones', to='geography.parish'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='subalmacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ubicaciones', to='institucion.subalmacen'),
        ),
        migrations.AlterUniqueTogether(
            name='ubicacion',
            unique_together={('nombre', 'parish', 'acueducto')},
        ),
    ]
