# Generated by Django 5.0 on 2026-01-02 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipality',
            options={'verbose_name': 'Municipio', 'verbose_name_plural': 'Municipios'},
        ),
        migrations.AlterModelOptions(
            name='parish',
            options={'verbose_name': 'Parroquia', 'verbose_name_plural': 'Parroquias'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'Estados', 'verbose_name_plural': 'Estados'},
        ),
    ]
