# Generated by Django 5.0.2 on 2026-02-06 03:32

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('productos.pipe',),
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('productos.pumpandmotor',),
        ),
        migrations.CreateModel(
            name='Tuberia',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('productos.pipe',),
        ),
    ]
