# Generated by Django 5.0.2 on 2026-01-18 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pumpandmotor',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_productos', to='catalogo.categoriaproducto'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_productos', to='catalogo.categoriaproducto'),
        ),
        migrations.AlterField(
            model_name='chemicalproduct',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_productos', to='catalogo.categoriaproducto'),
        ),
        migrations.AlterField(
            model_name='pipe',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_productos', to='catalogo.categoriaproducto'),
        ),
        migrations.RenameIndex(
            model_name='pumpandmotor',
            new_name='inventario__marca_i_0f8c1f_idx',
            old_name='inventario__marca_b5f1cc_idx',
        ),
        migrations.AlterField(
            model_name='pumpandmotor',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='catalogo.marca'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
