# Generated by Django 5.0.2 on 2026-01-18 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('inventario', '0002_alter_accessory_categoria_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alerta',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='acueducto',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='aprobador',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='movimiento',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='solicitante',
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
            ],
            options={
                'verbose_name': 'Categoría (compat)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalogo.categoriaproducto',),
        ),
        migrations.DeleteModel(
            name='Alerta',
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
        migrations.DeleteModel(
            name='OrdenCompra',
        ),
    ]
