# Generated by Django 6.0.1 on 2026-01-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_sucursal_codigo_alter_supplier_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
    ]
