# Generated by Django 5.0.2 on 2026-01-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_rename_inventario__marca_b5f1cc_idx_inventario__marca_i_0f8c1f_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pumpandmotor',
            new_name='inventario__marca_i_0f8c1f_idx',
            old_name='inventario__marca_b5f1cc_idx',
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo_movimiento',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('TRANSFER', 'Transferencia'), ('AJUSTE', 'Ajuste')], max_length=20),
        ),
    ]
