# Generated by Django 5.0.2 on 2026-01-25 22:24

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_rename_inventario__marca_b5f1cc_idx_inventario__marca_i_0f8c1f_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code for the tag', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='accessory',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Custom fields for flexible data storage'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chemicalproduct',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Custom fields for flexible data storage'),
        ),
        migrations.AddField(
            model_name='chemicalproduct',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipe',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Custom fields for flexible data storage'),
        ),
        migrations.AddField(
            model_name='pipe',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pumpandmotor',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Custom fields for flexible data storage'),
        ),
        migrations.AddField(
            model_name='pumpandmotor',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessory',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_products', to='inventario.tag'),
        ),
        migrations.AddField(
            model_name='chemicalproduct',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_products', to='inventario.tag'),
        ),
        migrations.AddField(
            model_name='pipe',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_products', to='inventario.tag'),
        ),
        migrations.AddField(
            model_name='pumpandmotor',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_products', to='inventario.tag'),
        ),
    ]
