# Generated by Django 5.0.2 on 2026-01-25 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_add_enhanced_functionality'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique configuration key (e.g., "email.smtp_host")', max_length=100)),
                ('value', models.JSONField(help_text='Configuration value in JSON format')),
                ('description', models.TextField(blank=True, help_text='Human-readable description of this configuration')),
                ('category', models.CharField(choices=[('general', 'General'), ('security', 'Seguridad'), ('notifications', 'Notificaciones'), ('email', 'Email'), ('maintenance', 'Mantenimiento'), ('performance', 'Rendimiento'), ('integration', 'Integración'), ('ui', 'Interfaz de Usuario')], default='general', help_text='Configuration category for organization', max_length=50)),
                ('environment', models.CharField(choices=[('development', 'Desarrollo'), ('testing', 'Pruebas'), ('staging', 'Staging'), ('production', 'Producción'), ('all', 'Todos los Entornos')], default='all', help_text='Environment where this configuration applies', max_length=20)),
                ('is_sensitive', models.BooleanField(default=False, help_text='Whether this configuration contains sensitive data (passwords, keys, etc.)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is currently active')),
                ('validation_schema', models.JSONField(blank=True, default=dict, help_text='JSON schema for validating the configuration value')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified this configuration', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
                'ordering': ['category', 'key', 'environment'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='inventario__categor_7b5397_idx'), models.Index(fields=['environment', 'is_active'], name='inventario__environ_96d260_idx'), models.Index(fields=['key', 'environment'], name='inventario__key_8e25c6_idx'), models.Index(fields=['is_sensitive'], name='inventario__is_sens_9804a0_idx')],
                'unique_together': {('key', 'environment')},
            },
        ),
    ]
