# Generated by Django 5.0.2 on 2026-02-05 15:20

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_add_inventory_segmentation'),
        ('inventario', '0007_add_system_configuration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='chemicalproduct',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='chemicalproduct',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='pipe',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='pipe',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='pumpandmotor',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='pumpandmotor',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='creado_en',
        ),
        migrations.AddField(
            model_name='accessory',
            name='certificaciones',
            field=models.JSONField(blank=True, default=list, help_text='Lista de certificaciones requeridas'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessory',
            name='es_critico',
            field=models.BooleanField(default=False, help_text='¿Es material crítico para operación?'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='lote',
            field=models.CharField(blank=True, help_text='Número de lote actual', max_length=50),
        ),
        migrations.AddField(
            model_name='accessory',
            name='nivel_criticidad',
            field=models.CharField(blank=True, choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto'), ('CRITICO', 'Crítico')], default='MEDIO', max_length=10),
        ),
        migrations.AddField(
            model_name='accessory',
            name='numero_serie',
            field=models.CharField(blank=True, help_text='Número de serie (si aplica)', max_length=100),
        ),
        migrations.AddField(
            model_name='accessory',
            name='prioridad_reposicion',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10),
        ),
        migrations.AddField(
            model_name='accessory',
            name='punto_reorden',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Nivel de stock donde se debe reordenar (calculado)', max_digits=12),
        ),
        migrations.AddField(
            model_name='accessory',
            name='requiere_certificacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accessory',
            name='stock_seguridad_dias',
            field=models.IntegerField(default=30, help_text='Días de stock de seguridad requeridos'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='tiempo_reposicion_dias',
            field=models.IntegerField(default=30, help_text='Tiempo estimado de reposición en días'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='tipo_inventario',
            field=models.CharField(choices=[('ESTRATEGICO', 'Estratégico Hídrico'), ('OPERACIONAL', 'Operacional'), ('CONSUMIBLE', 'Consumible'), ('ACTIVO_FIJO', 'Activo Fijo')], default='OPERACIONAL', help_text='Clasificación del inventario', max_length=20),
        ),
        migrations.AddField(
            model_name='accessory',
            name='ubicacion_fisica',
            field=models.CharField(blank=True, help_text='Ubicación física en almacén', max_length=200),
        ),
        migrations.AddField(
            model_name='accessory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización'),
        ),
        migrations.AddField(
            model_name='chemicalproduct',
            name='certificaciones',
            field=models.JSONField(blank=True, default=list, help_text='Lista de certificaciones requeridas'),
        ),
        migrations.AddField(
            model_name='chemicalproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chemicalproduct',
            name='es_critico',
            field=models.BooleanField(default=False, help_text='¿Es material crítico para operación?'),
        ),
        migrations.AddField(
            model_name='chemicalproduct',
            name='lote',
            field=models.CharField(blank=True, help_text='Número de lote actual', max_length=50),
        ),
        migrations.AddField(
            model_name='chemicalproduct',
            name='nivel_criticidad',
            field=models.CharField(blank=True, choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto'), ('CRITICO', 'Crítico')], default='MEDIO', max_length=10),
        ),
        migrations.AddField(
            model_name='chemicalproduct',
            name='numero_serie',
            field=models.CharField(blank=True, help_text='Número de serie (si aplica)', max_length=100),
        ),
        migrations.AddField(
            model_name='chemicalproduct',
            name='prioridad_reposicion',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10),
        ),
        migrations.AddField(
            model_name='chemicalproduct',
            name='punto_reorden',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Nivel de stock donde se debe reordenar (calculado)', max_digits=12),
        ),
        migrations.AddField(
            model_name='chemicalproduct',
            name='requiere_certificacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chemicalproduct',
            name='stock_seguridad_dias',
            field=models.IntegerField(default=30, help_text='Días de stock de seguridad requeridos'),
        ),
        migrations.AddField(
            model_name='chemicalproduct',
            name='tiempo_reposicion_dias',
            field=models.IntegerField(default=30, help_text='Tiempo estimado de reposición en días'),
        ),
        migrations.AddField(
            model_name='chemicalproduct',
            name='tipo_inventario',
            field=models.CharField(choices=[('ESTRATEGICO', 'Estratégico Hídrico'), ('OPERACIONAL', 'Operacional'), ('CONSUMIBLE', 'Consumible'), ('ACTIVO_FIJO', 'Activo Fijo')], default='OPERACIONAL', help_text='Clasificación del inventario', max_length=20),
        ),
        migrations.AddField(
            model_name='chemicalproduct',
            name='ubicacion_fisica',
            field=models.CharField(blank=True, help_text='Ubicación física en almacén', max_length=200),
        ),
        migrations.AddField(
            model_name='chemicalproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización'),
        ),
        migrations.AddField(
            model_name='pipe',
            name='certificaciones',
            field=models.JSONField(blank=True, default=list, help_text='Lista de certificaciones requeridas'),
        ),
        migrations.AddField(
            model_name='pipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipe',
            name='es_critico',
            field=models.BooleanField(default=False, help_text='¿Es material crítico para operación?'),
        ),
        migrations.AddField(
            model_name='pipe',
            name='lote',
            field=models.CharField(blank=True, help_text='Número de lote actual', max_length=50),
        ),
        migrations.AddField(
            model_name='pipe',
            name='nivel_criticidad',
            field=models.CharField(blank=True, choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto'), ('CRITICO', 'Crítico')], default='MEDIO', max_length=10),
        ),
        migrations.AddField(
            model_name='pipe',
            name='numero_serie',
            field=models.CharField(blank=True, help_text='Número de serie (si aplica)', max_length=100),
        ),
        migrations.AddField(
            model_name='pipe',
            name='prioridad_reposicion',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10),
        ),
        migrations.AddField(
            model_name='pipe',
            name='punto_reorden',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Nivel de stock donde se debe reordenar (calculado)', max_digits=12),
        ),
        migrations.AddField(
            model_name='pipe',
            name='requiere_certificacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pipe',
            name='stock_seguridad_dias',
            field=models.IntegerField(default=30, help_text='Días de stock de seguridad requeridos'),
        ),
        migrations.AddField(
            model_name='pipe',
            name='tiempo_reposicion_dias',
            field=models.IntegerField(default=30, help_text='Tiempo estimado de reposición en días'),
        ),
        migrations.AddField(
            model_name='pipe',
            name='tipo_inventario',
            field=models.CharField(choices=[('ESTRATEGICO', 'Estratégico Hídrico'), ('OPERACIONAL', 'Operacional'), ('CONSUMIBLE', 'Consumible'), ('ACTIVO_FIJO', 'Activo Fijo')], default='OPERACIONAL', help_text='Clasificación del inventario', max_length=20),
        ),
        migrations.AddField(
            model_name='pipe',
            name='ubicacion_fisica',
            field=models.CharField(blank=True, help_text='Ubicación física en almacén', max_length=200),
        ),
        migrations.AddField(
            model_name='pipe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización'),
        ),
        migrations.AddField(
            model_name='pumpandmotor',
            name='certificaciones',
            field=models.JSONField(blank=True, default=list, help_text='Lista de certificaciones requeridas'),
        ),
        migrations.AddField(
            model_name='pumpandmotor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pumpandmotor',
            name='es_critico',
            field=models.BooleanField(default=False, help_text='¿Es material crítico para operación?'),
        ),
        migrations.AddField(
            model_name='pumpandmotor',
            name='lote',
            field=models.CharField(blank=True, help_text='Número de lote actual', max_length=50),
        ),
        migrations.AddField(
            model_name='pumpandmotor',
            name='nivel_criticidad',
            field=models.CharField(blank=True, choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto'), ('CRITICO', 'Crítico')], default='MEDIO', max_length=10),
        ),
        migrations.AddField(
            model_name='pumpandmotor',
            name='prioridad_reposicion',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10),
        ),
        migrations.AddField(
            model_name='pumpandmotor',
            name='punto_reorden',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Nivel de stock donde se debe reordenar (calculado)', max_digits=12),
        ),
        migrations.AddField(
            model_name='pumpandmotor',
            name='requiere_certificacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pumpandmotor',
            name='stock_seguridad_dias',
            field=models.IntegerField(default=30, help_text='Días de stock de seguridad requeridos'),
        ),
        migrations.AddField(
            model_name='pumpandmotor',
            name='tiempo_reposicion_dias',
            field=models.IntegerField(default=30, help_text='Tiempo estimado de reposición en días'),
        ),
        migrations.AddField(
            model_name='pumpandmotor',
            name='tipo_inventario',
            field=models.CharField(choices=[('ESTRATEGICO', 'Estratégico Hídrico'), ('OPERACIONAL', 'Operacional'), ('CONSUMIBLE', 'Consumible'), ('ACTIVO_FIJO', 'Activo Fijo')], default='OPERACIONAL', help_text='Clasificación del inventario', max_length=20),
        ),
        migrations.AddField(
            model_name='pumpandmotor',
            name='ubicacion_fisica',
            field=models.CharField(blank=True, help_text='Ubicación física en almacén', max_length=200),
        ),
        migrations.AddField(
            model_name='pumpandmotor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización'),
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo se eliminó (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_products', to='catalogo.tag'),
        ),
        migrations.AlterField(
            model_name='chemicalproduct',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo se eliminó (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='chemicalproduct',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_products', to='catalogo.tag'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo se eliminó (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='pipe',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo se eliminó (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='pipe',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_products', to='catalogo.tag'),
        ),
        migrations.AlterField(
            model_name='pumpandmotor',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo se eliminó (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='pumpandmotor',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_products', to='catalogo.tag'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo se eliminó (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo se eliminó (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
