# Generated by Django 5.0.2 on 2026-02-05 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('geography', '0001_initial'),
        ('inventario', '0008_add_inventory_segmentation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización')),
                ('object_id', models.PositiveIntegerField()),
                ('valor_adquisicion', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_adquisicion', models.DateField()),
                ('vida_util_anos', models.IntegerField(help_text='Vida útil estimada en años')),
                ('valor_residual', models.DecimalField(decimal_places=2, default=0, help_text='Valor estimado al final de la vida útil', max_digits=12)),
                ('metodo_depreciacion', models.CharField(choices=[('LINEAL', 'Línea Recta'), ('ACELERADA', 'Acelerada'), ('UNIDADES', 'Unidades Producidas')], default='LINEAL', max_length=20)),
                ('depreciacion_acumulada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('codigo_activo', models.CharField(help_text='Código de etiqueta de activo fijo', max_length=50, unique=True)),
                ('estado_fisico', models.CharField(choices=[('EXCELENTE', 'Excelente'), ('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo'), ('FUERA_SERVICIO', 'Fuera de Servicio')], default='BUENO', max_length=20)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos_fijos_asignados', to=settings.AUTH_USER_MODEL)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos_fijos', to='geography.ubicacion')),
            ],
            options={
                'verbose_name': 'Activo Fijo',
                'verbose_name_plural': 'Activos Fijos',
                'indexes': [models.Index(fields=['codigo_activo'], name='inventario__codigo__783830_idx'), models.Index(fields=['estado_fisico'], name='inventario__estado__a78524_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaterialEstrategico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización')),
                ('object_id', models.PositiveIntegerField()),
                ('nivel_criticidad', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto'), ('CRITICO', 'Crítico')], default='MEDIO', max_length=10)),
                ('plan_contingencia', models.TextField(blank=True, help_text='Acciones a tomar en caso de desabastecimiento')),
                ('stock_seguridad_dias', models.IntegerField(default=90, help_text='Días de stock de seguridad estratégico (mayor al operacional)')),
                ('requiere_aprobacion_especial', models.BooleanField(default=True, help_text='¿Requiere aprobación especial para movimientos?')),
                ('alerta_stock_bajo', models.BooleanField(default=True, help_text='Enviar alerta proactiva de stock bajo')),
                ('alerta_vencimiento', models.BooleanField(default=True, help_text='Enviar alerta anticipada de vencimiento')),
                ('dias_alerta_vencimiento', models.IntegerField(default=60, help_text='Días de anticipación para alerta de vencimiento')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('proveedor_alternativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales_estrategicos_alternativos', to='inventario.supplier')),
                ('responsable', models.ForeignKey(help_text='Usuario responsable de este material', on_delete=django.db.models.deletion.PROTECT, related_name='materiales_estrategicos_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material Estratégico',
                'verbose_name_plural': 'Materiales Estratégicos',
                'indexes': [models.Index(fields=['nivel_criticidad'], name='inventario__nivel_c_173b28_idx'), models.Index(fields=['content_type', 'object_id'], name='inventario__content_a3c90f_idx')],
            },
        ),
    ]
