# Generated by Django 5.0.2 on 2026-02-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_add_strategic_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemicalproduct',
            name='consumo_mensual_promedio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Consumo mensual estimado en unidad de medida', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='chemicalproduct',
            name='dosis_tipica_ppm',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Dosis típica en ppm (partes por millón)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='chemicalproduct',
            name='uso_tratamiento',
            field=models.CharField(blank=True, choices=[('COAGULACION', 'Coagulación'), ('FLOCULACION', 'Floculación'), ('DESINFECCION', 'Desinfección'), ('AJUSTE_PH', 'Ajuste de pH'), ('OXIDACION', 'Oxidación'), ('OTRO', 'Otro')], help_text='Uso principal en el tratamiento de agua', max_length=50),
        ),
        migrations.AddField(
            model_name='pipe',
            name='certificacion_agua_potable',
            field=models.BooleanField(default=True, help_text='¿Certificado para uso en agua potable?'),
        ),
        migrations.AddField(
            model_name='pipe',
            name='tipo_red',
            field=models.CharField(blank=True, choices=[('PRINCIPAL', 'Red Principal'), ('SECUNDARIA', 'Red Secundaria'), ('ACOMETIDA', 'Acometida'), ('IMPULSION', 'Impulsión'), ('ADUCCION', 'Aducción')], help_text='Tipo de red donde se utiliza', max_length=20),
        ),
    ]
