# Generated by Django 5.0.2 on 2026-02-05 17:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('geography', '0001_initial'),
        ('inventario', '0010_extend_chemical_and_pipe_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockEquipo',
        ),
        migrations.DeleteModel(
            name='StockTuberia',
        ),
        migrations.AlterUniqueTogether(
            name='stockchemical',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stockchemical',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='stockchemical',
            name='ubicacion',
        ),
        migrations.AlterUniqueTogether(
            name='stockpipe',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stockpipe',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='stockpipe',
            name='ubicacion',
        ),
        migrations.AlterUniqueTogether(
            name='stockpumpandmotor',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stockpumpandmotor',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='stockpumpandmotor',
            name='ubicacion',
        ),
        migrations.CreateModel(
            name='StockEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'StockEquipo (compat)',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockTuberia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'StockTubería (compat)',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización')),
                ('object_id', models.PositiveIntegerField()),
                ('cantidad', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('lote', models.CharField(blank=True, help_text='Lote (si aplica)', max_length=50)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado_operativo', models.CharField(default='OPERATIVO', help_text='Estado operativo (principalmente para equipos)', max_length=20)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='geography.ubicacion')),
            ],
            options={
                'verbose_name': 'Stock Unificado',
                'verbose_name_plural': 'Stock Unificado',
            },
        ),
        migrations.DeleteModel(
            name='StockAccessory',
        ),
        migrations.DeleteModel(
            name='StockChemical',
        ),
        migrations.DeleteModel(
            name='StockPipe',
        ),
        migrations.DeleteModel(
            name='StockPumpAndMotor',
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['content_type', 'object_id'], name='inventario__content_45dbe1_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['ubicacion'], name='inventario__ubicaci_08ec00_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('content_type', 'object_id', 'ubicacion', 'lote')},
        ),
    ]
