# Generated by Django 5.0.2 on 2026-02-05 19:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_unify_stock_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='consumo_diario_estimado',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Consumo diario estimado para cálculos de reorden', max_digits=10),
        ),
        migrations.AddField(
            model_name='chemicalproduct',
            name='consumo_diario_estimado',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Consumo diario estimado para cálculos de reorden', max_digits=10),
        ),
        migrations.AddField(
            model_name='pipe',
            name='consumo_diario_estimado',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Consumo diario estimado para cálculos de reorden', max_digits=10),
        ),
        migrations.AddField(
            model_name='pumpandmotor',
            name='consumo_diario_estimado',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Consumo diario estimado para cálculos de reorden', max_digits=10),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='punto_reorden',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Nivel de stock donde se debe reordenar (calculado: consumo * (reposición + seguridad))', max_digits=12),
        ),
        migrations.AlterField(
            model_name='chemicalproduct',
            name='punto_reorden',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Nivel de stock donde se debe reordenar (calculado: consumo * (reposición + seguridad))', max_digits=12),
        ),
        migrations.AlterField(
            model_name='pipe',
            name='punto_reorden',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Nivel de stock donde se debe reordenar (calculado: consumo * (reposición + seguridad))', max_digits=12),
        ),
        migrations.AlterField(
            model_name='pumpandmotor',
            name='punto_reorden',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Nivel de stock donde se debe reordenar (calculado: consumo * (reposición + seguridad))', max_digits=12),
        ),
    ]
