# Generated by Django 5.0.2 on 2026-02-05 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0004_alter_materialestrategico_proveedor_alternativo'),
        ('productos', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_productos', to='proveedores.supplier'),
        ),
        migrations.AlterField(
            model_name='pumpandmotor',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_productos', to='proveedores.supplier'),
        ),
        migrations.AlterField(
            model_name='chemicalproduct',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_productos', to='proveedores.supplier'),
        ),
        migrations.AlterField(
            model_name='pipe',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_productos', to='proveedores.supplier'),
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
