# Generated by Django 5.0.2 on 2026-02-06 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('institucion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTelegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(help_text='Token del Bot de Telegram.', max_length=200)),
                ('activo', models.BooleanField(default=True, help_text='Activar/desactivar globalmente las notificaciones a Telegram.')),
            ],
            options={
                'verbose_name': 'Configuración de Telegram',
                'verbose_name_plural': 'Configuraciones de Telegram',
            },
        ),
        migrations.CreateModel(
            name='DestinatarioTelegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(help_text='ID del chat de Telegram del usuario.', max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True, help_text='El usuario desea recibir notificaciones en Telegram.')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='destinatario_telegram', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Destinatario de Telegram',
                'verbose_name_plural': 'Destinatarios de Telegram',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('mensaje', models.CharField(max_length=255)),
                ('tipo', models.CharField(default='INFO', max_length=50)),
                ('leida', models.BooleanField(default=False)),
                ('enviada', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('umbral_minimo', models.DecimalField(decimal_places=3, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('acueducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucion.acueducto')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Alerta de Stock',
                'verbose_name_plural': 'Alertas de Stock',
                'unique_together': {('content_type', 'object_id', 'acueducto')},
            },
        ),
    ]
