# Generated by Django 5.0.2 on 2026-01-18 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTelegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(help_text='Token del Bot de Telegram.', max_length=200)),
                ('activo', models.BooleanField(default=True, help_text='Activar/desactivar globalmente las notificaciones a Telegram.')),
            ],
            options={
                'verbose_name': 'Configuración de Telegram',
                'verbose_name_plural': 'Configuraciones de Telegram',
            },
        ),
        migrations.CreateModel(
            name='DestinatarioTelegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(help_text='ID del chat de Telegram del usuario.', max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True, help_text='El usuario desea recibir notificaciones en Telegram.')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='destinatario_telegram', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Destinatario de Telegram',
                'verbose_name_plural': 'Destinatarios de Telegram',
            },
        ),
    ]
