# Generated by Django 5.0.2 on 2026-01-18 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventario', '0002_alter_accessory_categoria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Correlativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Ej: ORDEN_COMPRA', max_length=50, unique=True)),
                ('prefijo', models.CharField(max_length=10)),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
                ('anio', models.PositiveIntegerField(default=2026)),
            ],
            options={
                'verbose_name': 'Correlativo',
                'verbose_name_plural': 'Correlativos',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('SOLICITADO', 'Solicitado'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('aprobador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('movimiento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orden_compra_v2', to='inventario.movimientoinventario')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('cantidad_pedida', models.DecimalField(decimal_places=3, max_digits=12)),
                ('cantidad_recibida', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('precio_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compras.ordencompra')),
            ],
            options={
                'verbose_name': 'Item de Orden',
                'verbose_name_plural': 'Items de Órdenes',
            },
        ),
    ]
