# Generated by Django 5.0.2 on 2026-02-06 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Correlativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización')),
                ('tipo', models.CharField(help_text='Ej: ORDEN_COMPRA', max_length=50, unique=True)),
                ('prefijo', models.CharField(max_length=10)),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
                ('anio', models.PositiveIntegerField(default=2026)),
            ],
            options={
                'verbose_name': 'Correlativo',
                'verbose_name_plural': 'Correlativos',
            },
        ),
        migrations.CreateModel(
            name='ItemOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Cuándo se eliminó (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación')),
                ('object_id', models.PositiveIntegerField()),
                ('cantidad_pedida', models.DecimalField(decimal_places=3, max_digits=12)),
                ('cantidad_recibida', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('precio_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Item de Orden',
                'verbose_name_plural': 'Items de Órdenes',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Cuándo se eliminó (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación')),
                ('codigo', models.CharField(blank=True, max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GLOBAL', 'Global')], default='INDIVIDUAL', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion_comercializacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_aprobacion_presupuesto', models.DateTimeField(blank=True, null=True)),
                ('fecha_aprobacion_finanzas', models.DateTimeField(blank=True, null=True)),
                ('fecha_ejecucion_compras', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE_COMERCIALIZACION', 'Pendiente Comercialización'), ('PENDIENTE_PRESUPUESTO', 'Pendiente Presupuesto'), ('PENDIENTE_FINANZAS', 'Pendiente Finanzas'), ('PENDIENTE_COMPRAS', 'Pendiente Compras'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=30)),
                ('notas', models.TextField(blank=True)),
                ('motivo_cancelacion', models.TextField(blank=True)),
                ('aprobado_comercializacion_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_aprobadas_comercializacion', to=settings.AUTH_USER_MODEL)),
                ('aprobado_finanzas_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_aprobadas_finanzas', to=settings.AUTH_USER_MODEL)),
                ('aprobado_presupuesto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_aprobadas_presupuesto', to=settings.AUTH_USER_MODEL)),
                ('ejecutado_compras_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_ejecutadas_compras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
