# Generated by Django 5.0.2 on 2026-02-06 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='movimiento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orden_compra_v2', to='stock.movimientoinventario'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='parent_order',
            field=models.ForeignKey(blank=True, help_text='Orden Global a la que pertenece esta orden individual', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_orders', to='compras.ordencompra'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra_solicitadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemorden',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compras.ordencompra'),
        ),
    ]
