# Generated by Django 5.0.2 on 2026-02-05 18:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_itemorden_deleted_at_ordencompra_deleted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='aprobador',
        ),
        migrations.AddField(
            model_name='correlativo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='correlativo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización'),
        ),
        migrations.AddField(
            model_name='itemorden',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemorden',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='aprobado_comercializacion_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_aprobadas_comercializacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='aprobado_finanzas_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_aprobadas_finanzas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='aprobado_presupuesto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_aprobadas_presupuesto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Cuándo se creó este registro', verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='ejecutado_compras_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_ejecutadas_compras', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='fecha_aprobacion_comercializacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='fecha_aprobacion_finanzas',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='fecha_aprobacion_presupuesto',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='fecha_ejecucion_compras',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='motivo_cancelacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='parent_order',
            field=models.ForeignKey(blank=True, help_text='Orden Global a la que pertenece esta orden individual', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_orders', to='compras.ordencompra'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='tipo',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GLOBAL', 'Global')], default='INDIVIDUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Última vez que se modificó', verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='itemorden',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo se eliminó (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo se eliminó (null = no eliminado)', null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='status',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE_COMERCIALIZACION', 'Pendiente Comercialización'), ('PENDIENTE_PRESUPUESTO', 'Pendiente Presupuesto'), ('PENDIENTE_FINANZAS', 'Pendiente Finanzas'), ('PENDIENTE_COMPRAS', 'Pendiente Compras'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=30),
        ),
    ]
