# Generated by Django 5.0.2 on 2026-02-05 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_refactor_purchase_workflow'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='movimiento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orden_compra_v2', to='stock.movimientoinventario'),
        ),
    ]
