# Generated by Django 5.0.2 on 2026-02-06 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flota', '0001_initial'),
        ('institucion', '0001_initial'),
        ('proveedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionvehiculo',
            name='unidad_destino',
            field=models.ForeignKey(help_text='Unidad organizacional de destino', on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos_asignados', to='institucion.unidadorganizacional'),
        ),
        migrations.AddField(
            model_name='asignacionvehiculo',
            name='usuario_asignado',
            field=models.ForeignKey(help_text='Usuario al que se asigna el vehículo', on_delete=django.db.models.deletion.PROTECT, related_name='historial_vehiculos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentovehiculo',
            name='subido_por',
            field=models.ForeignKey(help_text='Usuario que subió el documento', on_delete=django.db.models.deletion.PROTECT, related_name='documentos_vehiculo_subidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mantenimientovehiculo',
            name='proveedor_servicio',
            field=models.ForeignKey(blank=True, help_text='Proveedor/taller que realizó el mantenimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_realizados', to='proveedores.supplier'),
        ),
        migrations.AddField(
            model_name='mantenimientovehiculo',
            name='realizado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que supervisó el mantenimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_supervisados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mantenimientovehiculo',
            name='solicitado_por',
            field=models.ForeignKey(help_text='Usuario que solicitó el mantenimiento', on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos_solicitados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrocombustible',
            name='conductor',
            field=models.ForeignKey(blank=True, help_text='Conductor al momento de la carga', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargas_combustible', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrocombustible',
            name='registrado_por',
            field=models.ForeignKey(help_text='Usuario que registró la carga', on_delete=django.db.models.deletion.PROTECT, related_name='combustibles_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='tipovehiculo',
            index=models.Index(fields=['categoria'], name='flota_tipov_categor_6cd28c_idx'),
        ),
        migrations.AddIndex(
            model_name='tipovehiculo',
            index=models.Index(fields=['codigo'], name='flota_tipov_codigo_a9a65d_idx'),
        ),
        migrations.AddIndex(
            model_name='tipovehiculo',
            index=models.Index(fields=['activo'], name='flota_tipov_activo_9113f4_idx'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='almacen_actual',
            field=models.ForeignKey(blank=True, help_text='Almacén donde está resguardado (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos_flota', to='institucion.almacenregional'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='creado_por',
            field=models.ForeignKey(help_text='Usuario que registró el vehículo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='proveedor',
            field=models.ForeignKey(blank=True, help_text='Proveedor del vehículo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos_vendidos', to='proveedores.supplier'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='responsable_actual',
            field=models.ForeignKey(blank=True, help_text='Usuario actualmente responsable del vehículo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.ForeignKey(help_text='Tipo de vehículo', on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='flota.tipovehiculo'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='unidad_organizacional',
            field=models.ForeignKey(help_text='Unidad organizacional propietaria', on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos_flota', to='institucion.unidadorganizacional'),
        ),
        migrations.AddField(
            model_name='registrocombustible',
            name='vehiculo',
            field=models.ForeignKey(help_text='Vehículo', on_delete=django.db.models.deletion.CASCADE, related_name='registros_combustible', to='flota.vehiculo'),
        ),
        migrations.AddField(
            model_name='mantenimientovehiculo',
            name='vehiculo',
            field=models.ForeignKey(help_text='Vehículo', on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='flota.vehiculo'),
        ),
        migrations.AddField(
            model_name='documentovehiculo',
            name='vehiculo',
            field=models.ForeignKey(help_text='Vehículo al que pertenece el documento', on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='flota.vehiculo'),
        ),
        migrations.AddField(
            model_name='asignacionvehiculo',
            name='vehiculo',
            field=models.ForeignKey(help_text='Vehículo asignado', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='flota.vehiculo'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['codigo'], name='flota_vehic_codigo_392e1b_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['placa'], name='flota_vehic_placa_539155_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['serial_motor'], name='flota_vehic_serial__0090f2_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['estado'], name='flota_vehic_estado_59c4cb_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['tipo_vehiculo', 'estado'], name='flota_vehic_tipo_ve_42f7e7_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['unidad_organizacional', 'estado'], name='flota_vehic_unidad__f80399_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['responsable_actual'], name='flota_vehic_respons_4112c5_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['activo'], name='flota_vehic_activo_209781_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehiculo',
            constraint=models.UniqueConstraint(fields=('codigo',), name='unique_vehiculo_codigo'),
        ),
        migrations.AddIndex(
            model_name='registrocombustible',
            index=models.Index(fields=['vehiculo', '-fecha'], name='flota_regis_vehicul_e95188_idx'),
        ),
        migrations.AddIndex(
            model_name='registrocombustible',
            index=models.Index(fields=['fecha'], name='flota_regis_fecha_d63bdc_idx'),
        ),
        migrations.AddIndex(
            model_name='registrocombustible',
            index=models.Index(fields=['tipo_combustible'], name='flota_regis_tipo_co_66715f_idx'),
        ),
        migrations.AddIndex(
            model_name='mantenimientovehiculo',
            index=models.Index(fields=['vehiculo', '-fecha_programada'], name='flota_mante_vehicul_0ebeb3_idx'),
        ),
        migrations.AddIndex(
            model_name='mantenimientovehiculo',
            index=models.Index(fields=['tipo_mantenimiento', 'estado'], name='flota_mante_tipo_ma_33292f_idx'),
        ),
        migrations.AddIndex(
            model_name='mantenimientovehiculo',
            index=models.Index(fields=['fecha_programada'], name='flota_mante_fecha_p_467da8_idx'),
        ),
        migrations.AddIndex(
            model_name='mantenimientovehiculo',
            index=models.Index(fields=['estado'], name='flota_mante_estado_747772_idx'),
        ),
        migrations.AddIndex(
            model_name='documentovehiculo',
            index=models.Index(fields=['vehiculo', 'tipo_documento'], name='flota_docum_vehicul_3e36cc_idx'),
        ),
        migrations.AddIndex(
            model_name='documentovehiculo',
            index=models.Index(fields=['fecha_vencimiento'], name='flota_docum_fecha_v_b2cecf_idx'),
        ),
        migrations.AddIndex(
            model_name='documentovehiculo',
            index=models.Index(fields=['alertar_vencimiento', 'alerta_enviada'], name='flota_docum_alertar_2135b6_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionvehiculo',
            index=models.Index(fields=['vehiculo', '-fecha_inicio'], name='flota_asign_vehicul_ef7816_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionvehiculo',
            index=models.Index(fields=['usuario_asignado', 'activa'], name='flota_asign_usuario_1ee27c_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionvehiculo',
            index=models.Index(fields=['activa'], name='flota_asign_activa_2524bc_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionvehiculo',
            index=models.Index(fields=['fecha_inicio', 'fecha_fin'], name='flota_asign_fecha_i_df9407_idx'),
        ),
    ]
