# Generated by Django 5.0.2 on 2026-02-06 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación (Soft)'), ('RESTORE', 'Restauración'), ('HARD_DELETE', 'Eliminación Física'), ('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('LOGIN_FAILED', 'Intento de Inicio de Sesión Fallido'), ('PASSWORD_CHANGE', 'Cambio de Contraseña'), ('PASSWORD_RESET', 'Restablecimiento de Contraseña'), ('PERMISSION_GRANT', 'Concesión de Permiso'), ('PERMISSION_REVOKE', 'Revocación de Permiso'), ('ROLE_ASSIGN', 'Asignación de Rol'), ('ROLE_REMOVE', 'Eliminación de Rol'), ('CONFIG_CHANGE', 'Cambio de Configuración'), ('SYSTEM_MAINTENANCE', 'Mantenimiento del Sistema'), ('EXPORT', 'Exportación de Datos'), ('IMPORT', 'Importación de Datos'), ('BULK_UPDATE', 'Actualización Masiva'), ('BULK_DELETE', 'Eliminación Masiva'), ('ACCESS_DENIED', 'Acceso Denegado'), ('UNAUTHORIZED_ACCESS', 'Intento de Acceso No Autorizado')], help_text='Tipo de acción realizada', max_length=30)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID del objeto afectado', null=True)),
                ('object_repr', models.CharField(help_text='Representación textual del objeto afectado', max_length=255)),
                ('changes', models.JSONField(blank=True, help_text='Detalles de los cambios realizados en formato JSON', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP desde donde se realizó la acción', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent del navegador/cliente', null=True)),
                ('session_key', models.CharField(blank=True, help_text='Clave de sesión asociada', max_length=40, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Momento en que se realizó la acción')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Datos adicionales específicos del contexto')),
                ('risk_level', models.CharField(choices=[('LOW', 'Bajo'), ('MEDIUM', 'Medio'), ('HIGH', 'Alto'), ('CRITICAL', 'Crítico')], default='LOW', help_text='Nivel de riesgo de la acción para monitoreo de seguridad', max_length=10)),
                ('content_type', models.ForeignKey(blank=True, help_text='Tipo de contenido del objeto afectado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario que realizó la acción (nulo para acciones del sistema)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='auditoria_a_timesta_3349e8_idx'), models.Index(fields=['user', 'timestamp'], name='auditoria_a_user_id_c02936_idx'), models.Index(fields=['action', 'timestamp'], name='auditoria_a_action_046c23_idx'), models.Index(fields=['content_type', 'object_id'], name='auditoria_a_content_2f8c97_idx'), models.Index(fields=['ip_address', 'timestamp'], name='auditoria_a_ip_addr_cb7357_idx'), models.Index(fields=['risk_level', 'timestamp'], name='auditoria_a_risk_le_d7587b_idx')],
            },
        ),
    ]
