# Generated by Django 5.0.2 on 2026-01-25 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='Datos adicionales específicos del contexto'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Bajo'), ('MEDIUM', 'Medio'), ('HIGH', 'Alto'), ('CRITICAL', 'Crítico')], default='LOW', help_text='Nivel de riesgo de la acción para monitoreo de seguridad', max_length=10),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='session_key',
            field=models.CharField(blank=True, help_text='Clave de sesión asociada', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación (Soft)'), ('RESTORE', 'Restauración'), ('HARD_DELETE', 'Eliminación Física'), ('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('LOGIN_FAILED', 'Intento de Inicio de Sesión Fallido'), ('PASSWORD_CHANGE', 'Cambio de Contraseña'), ('PASSWORD_RESET', 'Restablecimiento de Contraseña'), ('PERMISSION_GRANT', 'Concesión de Permiso'), ('PERMISSION_REVOKE', 'Revocación de Permiso'), ('ROLE_ASSIGN', 'Asignación de Rol'), ('ROLE_REMOVE', 'Eliminación de Rol'), ('CONFIG_CHANGE', 'Cambio de Configuración'), ('SYSTEM_MAINTENANCE', 'Mantenimiento del Sistema'), ('EXPORT', 'Exportación de Datos'), ('IMPORT', 'Importación de Datos'), ('BULK_UPDATE', 'Actualización Masiva'), ('BULK_DELETE', 'Eliminación Masiva'), ('ACCESS_DENIED', 'Acceso Denegado'), ('UNAUTHORIZED_ACCESS', 'Intento de Acceso No Autorizado')], help_text='Tipo de acción realizada', max_length=30),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='changes',
            field=models.JSONField(blank=True, help_text='Detalles de los cambios realizados en formato JSON', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Tipo de contenido del objeto afectado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Dirección IP desde donde se realizó la acción', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID del objeto afectado', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_repr',
            field=models.CharField(help_text='Representación textual del objeto afectado', max_length=255),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='Momento en que se realizó la acción'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la acción (nulo para acciones del sistema)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True, help_text='User agent del navegador/cliente', null=True),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='auditoria_a_timesta_3349e8_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='auditoria_a_user_id_c02936_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'timestamp'], name='auditoria_a_action_046c23_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['content_type', 'object_id'], name='auditoria_a_content_2f8c97_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['ip_address', 'timestamp'], name='auditoria_a_ip_addr_cb7357_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['risk_level', 'timestamp'], name='auditoria_a_risk_le_d7587b_idx'),
        ),
    ]
