# Generated by Django 5.0.2 on 2026-02-06 03:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('institucion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_actual', models.CharField(help_text='Código único actual que evoluciona con traslados', max_length=100, unique=True)),
                ('codigo_original', models.CharField(help_text='Código original sin prefijos adicionales de traslados', max_length=100)),
                ('tipo_activo', models.CharField(choices=[('BOMBA', 'Bomba'), ('MOTOR', 'Motor'), ('TUBERIA', 'Tubería'), ('QUIMICO', 'Químico'), ('ACCESORIO', 'Accesorio'), ('EQUIPO', 'Equipo'), ('VALVULA', 'Válvula'), ('MEDIDOR', 'Medidor')], help_text='Tipo de activo para generación de código', max_length=20)),
                ('descripcion', models.TextField(help_text='Descripción detallada del activo')),
                ('estado', models.CharField(choices=[('EN_ALMACEN', 'En Almacén'), ('EN_TRANSITO', 'En Tránsito'), ('INSTALADO', 'Instalado'), ('EN_USO', 'En Uso'), ('MANTENIMIENTO', 'En Mantenimiento')], default='EN_ALMACEN', help_text='Estado actual del activo', max_length=20)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, help_text='Fecha de ingreso al sistema')),
                ('valor_unitario', models.DecimalField(decimal_places=2, help_text='Valor unitario del activo', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('numero_serie', models.CharField(blank=True, help_text='Número de serie del fabricante', max_length=100)),
                ('producto_inventario_id', models.PositiveIntegerField(help_text='ID del producto específico en el inventario')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, help_text='Usuario que actualizó por última vez el activo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activos_actualizados', to=settings.AUTH_USER_MODEL)),
                ('almacen_actual', models.ForeignKey(help_text='Almacén donde se encuentra actualmente', on_delete=django.db.models.deletion.CASCADE, related_name='activos_actuales', to='institucion.almacenregional')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó el registro del activo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activos_creados', to=settings.AUTH_USER_MODEL)),
                ('producto_inventario_type', models.ForeignKey(help_text='Tipo de producto del inventario (ChemicalProduct, Pipe, etc.)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Activo de Inventario',
                'verbose_name_plural': 'Activos de Inventario',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='AprobacionTraslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_aprobacion', models.CharField(choices=[('ORIGEN', 'Origen'), ('DESTINO', 'Destino')], help_text='Indica si aprueba como origen o como destino', max_length=10)),
                ('decision', models.CharField(choices=[('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], help_text='Decisión tomada', max_length=10)),
                ('fecha_decision', models.DateTimeField(auto_now_add=True)),
                ('comentarios', models.TextField(blank=True, help_text='Comentarios sobre la decisión')),
                ('aprobador', models.ForeignKey(help_text='Gerente que tomó la decisión', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aprobación de Traslado',
                'verbose_name_plural': 'Aprobaciones de Traslado',
                'ordering': ['-fecha_decision'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaAccesoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_auditoria', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del evento')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, help_text='Dirección IP desde donde se realizó la acción', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Información del navegador/cliente')),
                ('session_key', models.CharField(blank=True, help_text='ID de sesión de Django', max_length=40)),
                ('checksum', models.CharField(blank=True, help_text='Hash de integridad del registro', max_length=64)),
                ('contexto_adicional', models.JSONField(blank=True, default=dict, help_text='Contexto adicional de la operación en formato JSON')),
                ('accion', models.CharField(choices=[('LOGIN_SUCCESS', 'Inicio de Sesión Exitoso'), ('LOGIN_FAILED', 'Inicio de Sesión Fallido'), ('LOGOUT', 'Cierre de Sesión'), ('PASSWORD_CHANGE', 'Cambio de Contraseña'), ('PERMISSION_CHECK', 'Verificación de Permisos'), ('UNAUTHORIZED_ACCESS', 'Acceso No Autorizado'), ('SESSION_EXPIRED', 'Sesión Expirada'), ('ACCOUNT_LOCKED', 'Cuenta Bloqueada'), ('ACCOUNT_UNLOCKED', 'Cuenta Desbloqueada'), ('SECURITY_VIOLATION', 'Violación de Seguridad')], help_text='Tipo de evento de acceso', max_length=20)),
                ('recurso_accedido', models.CharField(blank=True, help_text='Recurso o URL accedida', max_length=200)),
                ('metodo_http', models.CharField(blank=True, help_text='Método HTTP utilizado', max_length=10)),
                ('codigo_respuesta', models.IntegerField(blank=True, help_text='Código de respuesta HTTP', null=True)),
                ('exitoso', models.BooleanField(default=True, help_text='Indica si el acceso fue exitoso')),
                ('motivo_fallo', models.TextField(blank=True, help_text='Motivo del fallo de acceso')),
                ('nivel_riesgo', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto'), ('CRITICO', 'Crítico')], default='BAJO', help_text='Nivel de riesgo del evento', max_length=10)),
                ('pais', models.CharField(blank=True, help_text='País desde donde se realizó el acceso', max_length=100)),
                ('ciudad', models.CharField(blank=True, help_text='Ciudad desde donde se realizó el acceso', max_length=100)),
                ('dispositivo', models.CharField(blank=True, help_text='Información del dispositivo utilizado', max_length=200)),
                ('usuario_objetivo', models.ForeignKey(blank=True, help_text='Usuario objetivo del evento', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditoria_acceso_objetivo', to=settings.AUTH_USER_MODEL)),
                ('usuario_responsable', models.ForeignKey(help_text='Usuario que realizó la acción', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría de Acceso al Sistema',
                'verbose_name_plural': 'Auditorías de Acceso al Sistema',
                'ordering': ['-fecha_auditoria'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaEstadoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_auditoria', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del evento')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, help_text='Dirección IP desde donde se realizó la acción', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Información del navegador/cliente')),
                ('session_key', models.CharField(blank=True, help_text='ID de sesión de Django', max_length=40)),
                ('checksum', models.CharField(blank=True, help_text='Hash de integridad del registro', max_length=64)),
                ('contexto_adicional', models.JSONField(blank=True, default=dict, help_text='Contexto adicional de la operación en formato JSON')),
                ('estado_anterior', models.CharField(choices=[('EN_ALMACEN', 'En Almacén'), ('EN_TRANSITO', 'En Tránsito'), ('INSTALADO', 'Instalado'), ('EN_USO', 'En Uso'), ('MANTENIMIENTO', 'En Mantenimiento')], help_text='Estado antes del cambio', max_length=20)),
                ('estado_nuevo', models.CharField(choices=[('EN_ALMACEN', 'En Almacén'), ('EN_TRANSITO', 'En Tránsito'), ('INSTALADO', 'Instalado'), ('EN_USO', 'En Uso'), ('MANTENIMIENTO', 'En Mantenimiento')], help_text='Estado después del cambio', max_length=20)),
                ('motivo', models.TextField(help_text='Motivo del cambio de estado')),
                ('exitoso', models.BooleanField(default=True, help_text='Indica si el cambio fue exitoso o fallido (por validación)')),
                ('activo', models.ForeignKey(help_text='Activo que cambió de estado', on_delete=django.db.models.deletion.CASCADE, related_name='auditoria_estados', to='operaciones.activoinventario')),
                ('usuario_responsable', models.ForeignKey(help_text='Usuario que realizó la acción', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría de Estado de Activo',
                'verbose_name_plural': 'Auditorías de Estados de Activos',
                'ordering': ['-fecha_auditoria'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaOperacionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_auditoria', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del evento')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, help_text='Dirección IP desde donde se realizó la acción', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Información del navegador/cliente')),
                ('session_key', models.CharField(blank=True, help_text='ID de sesión de Django', max_length=40)),
                ('checksum', models.CharField(blank=True, help_text='Hash de integridad del registro', max_length=64)),
                ('contexto_adicional', models.JSONField(blank=True, default=dict, help_text='Contexto adicional de la operación en formato JSON')),
                ('accion', models.CharField(help_text='Identificador de la operación (ej. TRANSFER_EXECUTE)', max_length=50)),
                ('descripcion', models.TextField(help_text='Descripción detallada de la operación')),
                ('entidades_afectadas', models.JSONField(default=list, help_text='Lista de entidades (Modelo:ID) alteradas por la operación')),
                ('parametros_operacion', models.JSONField(default=dict, help_text='Parámetros de entrada de la operación')),
                ('exitosa', models.BooleanField(default=True, help_text='Indica si la operación terminó correctamente')),
                ('errores', models.JSONField(blank=True, default=list, help_text='Lista de errores ocurridos (si falló)')),
                ('warnings', models.JSONField(blank=True, default=list, help_text='Lista de advertencias ocurridas')),
                ('duracion_segundos', models.FloatField(blank=True, help_text='Duración de la operación en segundos', null=True)),
                ('registros_procesados', models.IntegerField(default=0, help_text='Número total de registros afectados')),
                ('puede_revertir', models.BooleanField(default=False, help_text='Indica si la operación tiene lógica de reversión')),
                ('datos_rollback', models.JSONField(blank=True, default=dict, help_text='Datos necesarios para ejecutar un rollback')),
                ('usuario_responsable', models.ForeignKey(help_text='Usuario que realizó la acción', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría de Operación de Sistema',
                'verbose_name_plural': 'Auditorías de Operaciones de Sistema',
                'ordering': ['-fecha_auditoria'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudTraslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_solicitud', models.CharField(help_text='Número de solicitud único generado automáticamente', max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA_ORIGEN', 'Aprobada por Origen'), ('APROBADA_DESTINO', 'Aprobada por Destino'), ('APROBADA_COMPLETA', 'Completamente Aprobada'), ('EN_TRANSITO', 'En Tránsito'), ('COMPLETADA', 'Completada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', help_text='Estado actual del flujo de aprobación', max_length=20)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', help_text='Prioridad del traslado', max_length=10)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('fecha_limite', models.DateTimeField(help_text='Fecha máxima para completar el traslado')),
                ('motivo', models.TextField(help_text='Motivo detallado del traslado')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/transfers/')),
                ('activo', models.ForeignKey(help_text='Activo a trasladar', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_traslado', to='operaciones.activoinventario')),
                ('almacen_destino', models.ForeignKey(help_text='Almacén de destino', on_delete=django.db.models.deletion.CASCADE, related_name='traslados_entrada', to='institucion.almacenregional')),
                ('almacen_origen', models.ForeignKey(help_text='Almacén de origen', on_delete=django.db.models.deletion.CASCADE, related_name='traslados_salida', to='institucion.almacenregional')),
                ('aprobacion_destino', models.OneToOneField(blank=True, help_text='Aprobación del almacén de destino', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud_destino', to='operaciones.aprobaciontraslado')),
                ('aprobacion_origen', models.OneToOneField(blank=True, help_text='Aprobación del almacén de origen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud_origen', to='operaciones.aprobaciontraslado')),
                ('ejecutor', models.ForeignKey(blank=True, help_text='Usuario que ejecuta el traslado físico', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traslados_ejecutados', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(help_text='Usuario que solicita el traslado', on_delete=django.db.models.deletion.PROTECT, related_name='traslados_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Traslado',
                'verbose_name_plural': 'Solicitudes de Traslado',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='HistorialMovimientoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('INGRESO_INICIAL', 'Ingreso Inicial'), ('TRASLADO_ALMACEN', 'Traslado entre Almacenes'), ('TRASLADO_EJECUTADO', 'Traslado Ejecutado'), ('ROLLBACK_TRASLADO', 'Rollback de Traslado'), ('CAMBIO_ESTADO', 'Cambio de Estado'), ('CAMBIO_ESTADO_AUTO_TRANSFER_APPROVED', 'Cambio de Estado Automático - Traslado Aprobado'), ('CAMBIO_ESTADO_AUTO_TRANSFER_COMPLETED', 'Cambio de Estado Automático - Traslado Completado'), ('CAMBIO_ESTADO_AUTO_MAINTENANCE_REQUIRED', 'Cambio de Estado Automático - Mantenimiento Requerido'), ('INSTALACION', 'Instalación'), ('RETIRO', 'Retiro'), ('MANTENIMIENTO_ENTRADA', 'Entrada a Mantenimiento'), ('MANTENIMIENTO_SALIDA', 'Salida de Mantenimiento'), ('CORRECCION_INVENTARIO', 'Corrección de Inventario'), ('AUDITORIA_FISICA', 'Auditoría Física'), ('BAJA_ACTIVO', 'Baja de Activo'), ('REACTIVACION_ACTIVO', 'Reactivación de Activo')], help_text='Tipo de movimiento realizado', max_length=50)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del movimiento')),
                ('estado_anterior', models.CharField(choices=[('EN_ALMACEN', 'En Almacén'), ('EN_TRANSITO', 'En Tránsito'), ('INSTALADO', 'Instalado'), ('EN_USO', 'En Uso'), ('MANTENIMIENTO', 'En Mantenimiento')], help_text='Estado anterior del activo', max_length=20)),
                ('estado_nuevo', models.CharField(choices=[('EN_ALMACEN', 'En Almacén'), ('EN_TRANSITO', 'En Tránsito'), ('INSTALADO', 'Instalado'), ('EN_USO', 'En Uso'), ('MANTENIMIENTO', 'En Mantenimiento')], help_text='Estado nuevo del activo', max_length=20)),
                ('codigo_anterior', models.CharField(help_text='Código anterior del activo', max_length=100)),
                ('codigo_nuevo', models.CharField(help_text='Código nuevo del activo', max_length=100)),
                ('motivo', models.TextField(help_text='Motivo del movimiento')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata for the movement operation')),
                ('activo', models.ForeignKey(help_text='Activo al que pertenece este movimiento', on_delete=django.db.models.deletion.CASCADE, related_name='historial_movimientos', to='operaciones.activoinventario')),
                ('almacen_destino', models.ForeignKey(blank=True, help_text='Almacén de destino (si aplica)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_destino', to='institucion.almacenregional')),
                ('almacen_origen', models.ForeignKey(blank=True, help_text='Almacén de origen (si aplica)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_origen', to='institucion.almacenregional')),
                ('usuario_responsable', models.ForeignKey(help_text='Usuario responsable del movimiento', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_responsable', to=settings.AUTH_USER_MODEL)),
                ('solicitud_traslado', models.ForeignKey(blank=True, help_text='Solicitud de traslado asociada (si aplica)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_asociados', to='operaciones.solicitudtraslado')),
            ],
            options={
                'verbose_name': 'Historial de Movimiento de Activo',
                'verbose_name_plural': 'Historial de Movimientos de Activos',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_auditoria', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del evento')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, help_text='Dirección IP desde donde se realizó la acción', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Información del navegador/cliente')),
                ('session_key', models.CharField(blank=True, help_text='ID de sesión de Django', max_length=40)),
                ('checksum', models.CharField(blank=True, help_text='Hash de integridad del registro', max_length=64)),
                ('contexto_adicional', models.JSONField(blank=True, default=dict, help_text='Contexto adicional de la operación en formato JSON')),
                ('accion', models.CharField(choices=[('APPROVAL_GRANTED', 'Aprobación Otorgada'), ('APPROVAL_REJECTED', 'Aprobación Rechazada'), ('APPROVAL_REVOKED', 'Aprobación Revocada')], help_text='Tipo de acción realizada', max_length=20)),
                ('comentarios', models.TextField(blank=True, help_text='Comentarios del aprobador')),
                ('motivo_rechazo', models.TextField(blank=True, help_text='Motivo técnico del rechazo')),
                ('aprobacion', models.ForeignKey(blank=True, help_text='Vínculo al registro de aprobación (si fue exitosa)', null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.aprobaciontraslado')),
                ('usuario_responsable', models.ForeignKey(help_text='Usuario que realizó la acción', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_responsable', to=settings.AUTH_USER_MODEL)),
                ('solicitud_traslado', models.ForeignKey(help_text='Solicitud en la que se tomó la decisión', on_delete=django.db.models.deletion.CASCADE, related_name='auditoria_aprobaciones', to='operaciones.solicitudtraslado')),
            ],
            options={
                'verbose_name': 'Auditoría de Aprobación',
                'verbose_name_plural': 'Auditorías de Aprobaciones',
                'ordering': ['-fecha_auditoria'],
            },
        ),
        migrations.AddField(
            model_name='aprobaciontraslado',
            name='solicitud',
            field=models.ForeignKey(help_text='Solicitud a la que pertenece esta aprobación', on_delete=django.db.models.deletion.CASCADE, related_name='aprobaciones', to='operaciones.solicitudtraslado'),
        ),
        migrations.AddIndex(
            model_name='activoinventario',
            index=models.Index(fields=['codigo_actual'], name='operaciones_codigo__e96c75_idx'),
        ),
        migrations.AddIndex(
            model_name='activoinventario',
            index=models.Index(fields=['codigo_original'], name='operaciones_codigo__0864fe_idx'),
        ),
        migrations.AddIndex(
            model_name='activoinventario',
            index=models.Index(fields=['almacen_actual', 'estado'], name='operaciones_almacen_e1af71_idx'),
        ),
        migrations.AddIndex(
            model_name='activoinventario',
            index=models.Index(fields=['tipo_activo', 'estado'], name='operaciones_tipo_ac_c0a348_idx'),
        ),
        migrations.AddIndex(
            model_name='activoinventario',
            index=models.Index(fields=['fecha_ingreso'], name='operaciones_fecha_i_5e2acc_idx'),
        ),
        migrations.AddIndex(
            model_name='activoinventario',
            index=models.Index(fields=['producto_inventario_type', 'producto_inventario_id'], name='operaciones_product_ba197e_idx'),
        ),
        migrations.AddConstraint(
            model_name='activoinventario',
            constraint=models.UniqueConstraint(fields=('codigo_actual',), name='unique_activo_codigo_actual'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaccesosistema',
            index=models.Index(fields=['accion', '-fecha_auditoria'], name='idx_aud_acc_accion_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaccesosistema',
            index=models.Index(fields=['usuario_responsable', '-fecha_auditoria'], name='idx_aud_acc_usuario_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaccesosistema',
            index=models.Index(fields=['usuario_objetivo', '-fecha_auditoria'], name='idx_aud_acc_objetivo_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaccesosistema',
            index=models.Index(fields=['exitoso', '-fecha_auditoria'], name='idx_aud_acc_exitoso_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaccesosistema',
            index=models.Index(fields=['nivel_riesgo', '-fecha_auditoria'], name='idx_aud_acc_riesgo_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaccesosistema',
            index=models.Index(fields=['direccion_ip', '-fecha_auditoria'], name='idx_aud_acc_ip_fecha'),
        ),
        migrations.AddConstraint(
            model_name='auditoriaaccesosistema',
            constraint=models.CheckConstraint(check=models.Q(('codigo_respuesta__isnull', True), models.Q(('codigo_respuesta__gte', 100), ('codigo_respuesta__lt', 600)), _connector='OR'), name='operaciones_acceso_resp_valid'),
        ),
        migrations.AddIndex(
            model_name='auditoriaestadoactivo',
            index=models.Index(fields=['activo', '-fecha_auditoria'], name='idx_aud_est_activo_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaestadoactivo',
            index=models.Index(fields=['estado_nuevo', '-fecha_auditoria'], name='idx_aud_est_nuevo_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaestadoactivo',
            index=models.Index(fields=['exitoso', '-fecha_auditoria'], name='idx_aud_est_exitoso_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaoperacionsistema',
            index=models.Index(fields=['accion', '-fecha_auditoria'], name='idx_aud_op_acc_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaoperacionsistema',
            index=models.Index(fields=['exitosa', '-fecha_auditoria'], name='idx_aud_op_exit_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaoperacionsistema',
            index=models.Index(fields=['puede_revertir', '-fecha_auditoria'], name='idx_aud_op_rev_fecha'),
        ),
        migrations.AddIndex(
            model_name='solicitudtraslado',
            index=models.Index(fields=['estado', '-fecha_solicitud'], name='operaciones_estado_0ea657_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudtraslado',
            index=models.Index(fields=['numero_solicitud'], name='operaciones_numero__0030d4_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudtraslado',
            index=models.Index(fields=['almacen_origen', 'estado'], name='operaciones_almacen_7b6fc2_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudtraslado',
            index=models.Index(fields=['almacen_destino', 'estado'], name='operaciones_almacen_e309e8_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudtraslado',
            index=models.Index(fields=['prioridad', 'estado'], name='operaciones_priorid_e257f5_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudtraslado',
            index=models.Index(fields=['fecha_limite'], name='operaciones_fecha_l_73faab_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudtraslado',
            index=models.Index(fields=['aprobacion_origen', 'estado'], name='operaciones_aprobac_dfaa1b_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudtraslado',
            index=models.Index(fields=['aprobacion_destino', 'estado'], name='operaciones_aprobac_27b3f8_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudtraslado',
            index=models.Index(fields=['estado', 'fecha_limite'], name='operaciones_estado_1fd41d_idx'),
        ),
        migrations.AddIndex(
            model_name='historialmovimientoactivo',
            index=models.Index(fields=['activo', '-fecha_movimiento'], name='idx_hist_activo_fecha'),
        ),
        migrations.AddIndex(
            model_name='historialmovimientoactivo',
            index=models.Index(fields=['almacen_origen', '-fecha_movimiento'], name='idx_hist_origen_fecha'),
        ),
        migrations.AddIndex(
            model_name='historialmovimientoactivo',
            index=models.Index(fields=['almacen_destino', '-fecha_movimiento'], name='idx_hist_destino_fecha'),
        ),
        migrations.AddIndex(
            model_name='historialmovimientoactivo',
            index=models.Index(fields=['tipo_movimiento', '-fecha_movimiento'], name='idx_hist_tipo_fecha'),
        ),
        migrations.AddIndex(
            model_name='historialmovimientoactivo',
            index=models.Index(fields=['usuario_responsable', '-fecha_movimiento'], name='idx_hist_usuario_fecha'),
        ),
        migrations.AddConstraint(
            model_name='historialmovimientoactivo',
            constraint=models.CheckConstraint(check=models.Q(('fecha_movimiento__isnull', False)), name='operaciones_hist_fecha_mov'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaprobacion',
            index=models.Index(fields=['solicitud_traslado', '-fecha_auditoria'], name='idx_aud_apr_sol_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaprobacion',
            index=models.Index(fields=['accion', '-fecha_auditoria'], name='idx_aud_apr_acc_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaprobacion',
            index=models.Index(fields=['aprobacion', '-fecha_auditoria'], name='idx_aud_apr_apr_fecha'),
        ),
        migrations.AddIndex(
            model_name='aprobaciontraslado',
            index=models.Index(fields=['solicitud', 'tipo_aprobacion'], name='operaciones_solicit_17664e_idx'),
        ),
        migrations.AddIndex(
            model_name='aprobaciontraslado',
            index=models.Index(fields=['aprobador', 'decision'], name='operaciones_aprobad_551d56_idx'),
        ),
        migrations.AddIndex(
            model_name='aprobaciontraslado',
            index=models.Index(fields=['fecha_decision'], name='operaciones_fecha_d_537378_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aprobaciontraslado',
            unique_together={('solicitud', 'tipo_aprobacion')},
        ),
    ]
